---
execute:
  skip: true
authors:
- name: Monika Doerig
doi: 10.5281/zenodo.18728802
github: https://github.com/neurodesk/neurodeskedu/blob/main/books/examples/workflows/PyBIDS.ipynb
edit_url: https://github.com/neurodesk/neurodeskedu/edit/main/books/examples/workflows/PyBIDS.ipynb
downloads:
- url: /edu/_sources/examples/workflows/PyBIDS.ipynb
  title: Download source notebook
  filename: PyBIDS.ipynb
  static: false
---
#  PyBIDS

:::{admonition} Reviewed
:class: nd-review-badge nd-review-badge--reviewed

[review issue](<https://github.com/neurodesk/neurodeskedu-reviews/issues/35>) · [@air2310](<https://github.com/air2310>)
:::

:::{dropdown} Run this notebook
:class: nd-launch

- [Run in Australia](<https://play.neurodesk.cloud.edu.au/hub/user-redirect/git-pull?repo=https%3A//github.com/neurodesk/neurodeskedu&urlpath=lab/tree/neurodeskedu/books/examples/workflows/PyBIDS.ipynb&branch=main>)
- [Run in Europe](<https://play-europe.neurodesk.org/hub/user-redirect/git-pull?repo=https%3A//github.com/neurodesk/neurodeskedu&urlpath=lab/tree/neurodeskedu/books/examples/workflows/PyBIDS.ipynb&branch=main>)
- [Run in America](<https://play-america.neurodesk.org/hub/user-redirect/git-pull?repo=https%3A//github.com/neurodesk/neurodeskedu&urlpath=lab/tree/neurodeskedu/books/examples/workflows/PyBIDS.ipynb&branch=main>)
- [Run in Global Server 1](<https://play-europe.neurodesk.org/hub/user-redirect/git-pull?repo=https%3A//github.com/neurodesk/neurodeskedu&urlpath=lab/tree/neurodeskedu/books/examples/workflows/PyBIDS.ipynb&branch=main>)
- [Run in Global Server 2](<https://edu.neurodesk.org/hub/user-redirect/git-pull?repo=https%3A//github.com/neurodesk/neurodeskedu&urlpath=lab/tree/neurodeskedu/books/examples/workflows/PyBIDS.ipynb&branch=main>)
:::

## A Python API for working with BIDS datasets

**Author:** Monika Doerig

**Date:** 4 June 2025

**License:** 
<div style="margin-top: 10px;">
    <a href="https://opensource.org/licenses/MIT" target="_blank" style="color: #0066cc;">
        <i class="fas fa-balance-scale"></i> MIT License
    </a>
</div>


**Note:** If this notebook uses neuroimaging tools from Neurocontainers, those tools retain their original licenses. Please see <a href="https://neurodesk.org/overview/how-to-cite-us/" target="_blank" style="color: #0066cc;">Neurodesk citation guidelines</a> for details.

### Citation and Resources:

#### Data from OpenNeuro
- Gorgolewski KJ and Storkey A and Bastin ME and Whittle IR and Wardlaw JM and Pernet CR (2022). A test-retest fMRI dataset for motor, language and spatial attention functions. OpenNeuro. [Dataset] doi: doi[10.18112/openneuro.ds000114.v1.0.2](https://doi.org/10.18112/openneuro.ds000114.v1.0.2)

#### Tools included in this workflow
**pyBIDS**: 

- Yarkoni et al., (2019). PyBIDS: Python tools for BIDS datasets. Journal of Open Source Software, 4(40), 1294, [https://doi.org/10.21105/joss.01294](https://doi.org/10.21105/joss.01294)

- Yarkoni, T., Markiewicz, C. J., de la Vega, A., Gorgolewski, K. J., Salo, T., Gau, R., Halchenko, Y. O., Papadopoulos Orfanos, D., Esteban, O., McNamara, Q., DeStasio, K., Poline, J.-B., Johnson, H., Kalenkovich, E., Petrov, D., Nielson, D. M., James Kent, Kent, J. D., Appelhoff, S., … pierre-nedelec. (2024). PyBIDS: Python tools for BIDS datasets (0.18.1). Zenodo. [https://doi.org/10.5281/zenodo.14285569](https://doi.org/10.5281/zenodo.14285569)

#### Educational resources
- This example is highly inspired by the [pybids documentation](https://bids-standard.github.io/pybids/index.html)

## Installation

PyBIDS simplifies the process of querying, summarizing, and managing data for neuroimaging researchers using the BIDS standard. Several Python packages for neuroimaging analysis—such as Nipype and Nilearn—are designed to integrate seamlessly with BIDS-formatted datasets

In [1]:
%%capture
! pip install pybids

## Data download

In [2]:
PATTERN = "sub-0[1-5]"
! datalad install https://github.com/OpenNeuroDatasets/ds000114.git 
! cd ds000114 && datalad get $PATTERN

Cloning:   0%|                             | 0.00/2.00 [00:00<?, ? candidates/s]

Enumerating: 0.00 Objects [00:00, ? Objects/s]

Counting:   0%|                                | 0.00/820 [00:00<?, ? Objects/s]

Compressing:   0%|                             | 0.00/616 [00:00<?, ? Objects/s]

Receiving:   0%|                             | 0.00/2.17k [00:00<?, ? Objects/s]

Resolving:   0%|                                | 0.00/147 [00:00<?, ? Deltas/s]

[INFO   ] Remote origin not usable by git-annex; setting annex-ignore
[INFO   ] https://github.com/OpenNeuroDatasets/ds000114.git/config download failed: Not Found

[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
| 		datalad siblings -d "/home/jovyan/workspace/books/examples/workflows/ds000114" enable -s s3-PRIVATE
install(ok): /home/jovyan/workspace/books/examples/workflows/ds000114 (dataset)

Total:   0%|                                   | 0.00/2.17G [00:00<?, ? Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   0%|            | 0.00/8.50M [00:00<?, ? Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   0%|    | 33.4k/8.50M [00:00<00:53, 159k Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   1%|    | 68.2k/8.50M [00:00<00:52, 161k Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   2%|     | 138k/8.50M [00:00<00:35, 238k Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   3%|▏    | 277k/8.50M [00:00<00:20, 405k Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   7%|▎    | 573k/8.50M [00:01<00:10, 764k Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  13%|▍  | 1.15M/8.50M [00:01<00:05, 1.43M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  27%|▊  | 2.30M/8.50M [00:01<00:02, 2.97M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  38%|█▏ | 3.20M/8.50M [00:01<00:01, 4.13M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  55%|█▋ | 4.66M/8.50M [00:01<00:00, 5.69M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  72%|██▏| 6.12M/8.50M [00:01<00:00, 7.59M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  95%|██▊| 8.10M/8.50M [00:01<00:00, 8.33M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   0%|            | 0.00/8.50M [00:00<?, ? Bytes/s]

Total:   0%|                          | 8.50M/2.17G [00:03<13:57, 2.58M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   0%|            | 0.00/99.9M [00:00<?, ? Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   2%|   | 1.98M/99.9M [00:00<00:19, 4.90M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   3%|   | 3.23M/99.9M [00:00<00:14, 6.88M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   5%|▏  | 4.96M/99.9M [00:00<00:12, 7.43M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   7%|▏  | 7.18M/99.9M [00:00<00:10, 8.66M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   9%|▎  | 9.23M/99.9M [00:01<00:10, 9.04M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  12%|▎  | 11.5M/99.9M [00:01<00:09, 9.52M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  14%|▍  | 13.6M/99.9M [00:01<00:08, 9.78M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  15%|▍  | 14.7M/99.9M [00:01<00:08, 9.72M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  16%|▍  | 16.2M/99.9M [00:01<00:07, 10.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  18%|▌  | 18.4M/99.9M [00:01<00:07, 10.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  21%|▋  | 21.0M/99.9M [00:02<00:07, 11.2M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  23%|▋  | 23.3M/99.9M [00:02<00:06, 11.2M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  26%|▊  | 25.5M/99.9M [00:02<00:06, 10.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  28%|▊  | 27.7M/99.9M [00:02<00:06, 10.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  30%|▉  | 30.0M/99.9M [00:03<00:06, 10.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  32%|▉  | 32.1M/99.9M [00:03<00:06, 10.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  34%|█  | 34.2M/99.9M [00:03<00:06, 10.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  36%|█  | 36.2M/99.9M [00:03<00:06, 10.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  39%|█▏ | 38.5M/99.9M [00:03<00:05, 10.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  41%|█▏ | 40.7M/99.9M [00:04<00:05, 10.4M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  43%|█▎ | 43.1M/99.9M [00:04<00:05, 10.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  46%|█▎ | 45.5M/99.9M [00:04<00:05, 10.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  48%|█▍ | 47.8M/99.9M [00:04<00:04, 10.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  50%|█▌ | 50.2M/99.9M [00:04<00:04, 11.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  53%|█▌ | 52.6M/99.9M [00:05<00:04, 11.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  55%|█▋ | 54.9M/99.9M [00:05<00:04, 11.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  57%|█▋ | 57.4M/99.9M [00:05<00:03, 11.2M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  60%|█▊ | 59.8M/99.9M [00:05<00:03, 11.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  62%|█▊ | 61.9M/99.9M [00:05<00:03, 10.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  65%|█▉ | 64.4M/99.9M [00:06<00:03, 11.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  66%|█▉ | 65.6M/99.9M [00:06<00:03, 11.2M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  67%|██ | 67.1M/99.9M [00:06<00:02, 11.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  70%|██ | 69.5M/99.9M [00:06<00:02, 11.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  71%|██ | 70.8M/99.9M [00:06<00:02, 11.5M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  72%|██▏| 72.1M/99.9M [00:06<00:02, 12.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  75%|██▏| 74.9M/99.9M [00:07<00:02, 12.4M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  78%|██▎| 77.5M/99.9M [00:07<00:01, 12.4M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  79%|██▎| 79.1M/99.9M [00:07<00:01, 13.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  82%|██▍| 81.7M/99.9M [00:07<00:01, 13.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  83%|██▍| 83.1M/99.9M [00:07<00:01, 13.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  86%|██▌| 85.7M/99.9M [00:07<00:01, 13.2M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  88%|██▋| 88.1M/99.9M [00:08<00:00, 12.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  90%|██▋| 89.5M/99.9M [00:08<00:00, 13.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  91%|██▋| 90.9M/99.9M [00:08<00:00, 13.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  92%|██▊| 92.2M/99.9M [00:08<00:00, 13.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  94%|██▊| 93.6M/99.9M [00:08<00:00, 13.4M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  96%|██▉| 96.3M/99.9M [00:08<00:00, 13.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  99%|██▉| 98.9M/99.9M [00:08<00:00, 13.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   0%|            | 0.00/99.9M [00:00<?, ? Bytes/s]

Total:   5%|█▎                         | 108M/2.17G [00:12<04:04, 8.45M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/22.3M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:  14%|▍  | 3.14M/22.3M [00:00<00:01, 15.2M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  29%|▊  | 6.45M/22.3M [00:00<00:01, 14.6M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  40%|█▏ | 9.01M/22.3M [00:00<00:00, 13.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  51%|█▌ | 11.4M/22.3M [00:00<00:00, 12.6M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  57%|█▋ | 12.6M/22.3M [00:00<00:00, 12.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  68%|██ | 15.1M/22.3M [00:01<00:00, 12.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  73%|██▏| 16.4M/22.3M [00:01<00:00, 12.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  79%|██▎| 17.6M/22.3M [00:01<00:00, 11.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  85%|██▌| 19.0M/22.3M [00:01<00:00, 12.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  91%|██▋| 20.3M/22.3M [00:01<00:00, 12.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  97%|██▉| 21.7M/22.3M [00:01<00:00, 12.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/22.3M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/23.8M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   5%|▏  | 1.20M/23.8M [00:00<00:01, 12.0M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  12%|▎  | 2.97M/23.8M [00:00<00:01, 15.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  20%|▌  | 4.64M/23.8M [00:00<00:01, 10.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  26%|▊  | 6.12M/23.8M [00:00<00:01, 12.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  38%|█▏ | 9.12M/23.8M [00:00<00:01, 13.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  49%|█▍ | 11.6M/23.8M [00:01<00:01, 10.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  59%|█▊ | 14.1M/23.8M [00:01<00:00, 12.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  70%|██ | 16.6M/23.8M [00:01<00:00, 10.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  77%|██▎| 18.4M/23.8M [00:01<00:00, 12.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  87%|██▌| 20.6M/23.8M [00:01<00:00, 11.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  96%|██▊| 22.8M/23.8M [00:01<00:00, 11.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/23.8M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/30.7M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   4%|   | 1.28M/30.7M [00:00<00:02, 12.7M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   9%|▎  | 2.62M/30.7M [00:00<00:02, 13.2M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  13%|▍  | 3.99M/30.7M [00:00<00:01, 13.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  20%|▌  | 6.17M/30.7M [00:00<00:02, 11.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  28%|▊  | 8.76M/30.7M [00:00<00:01, 11.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  35%|█  | 10.8M/30.7M [00:00<00:01, 10.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  45%|█▎ | 14.0M/30.7M [00:01<00:01, 12.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  50%|█▍ | 15.3M/30.7M [00:01<00:01, 10.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  55%|█▋ | 16.8M/30.7M [00:01<00:01, 11.0M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  60%|█▊ | 18.3M/30.7M [00:01<00:01, 10.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  64%|█▉ | 19.5M/30.7M [00:01<00:01, 10.6M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  68%|██ | 21.0M/30.7M [00:01<00:00, 11.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  73%|██▏| 22.4M/30.7M [00:01<00:00, 12.0M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  81%|██▍| 24.8M/30.7M [00:02<00:00, 8.14M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  90%|██▋| 27.7M/30.7M [00:02<00:00, 9.13M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  98%|██▉| 30.2M/30.7M [00:02<00:00, 9.98M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/30.7M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/11.8M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:  24%|▋  | 2.80M/11.8M [00:00<00:00, 13.2M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  36%|█  | 4.32M/11.8M [00:00<00:00, 14.0M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  58%|█▋ | 6.82M/11.8M [00:00<00:00, 9.97M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  70%|██ | 8.28M/11.8M [00:00<00:00, 11.0M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  88%|██▋| 10.4M/11.8M [00:00<00:00, 10.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/11.8M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/10.2M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:  29%|▊  | 2.91M/10.2M [00:00<00:00, 13.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  45%|█▎ | 4.57M/10.2M [00:00<00:00, 10.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  61%|█▊ | 6.16M/10.2M [00:00<00:00, 11.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  84%|██▌| 8.49M/10.2M [00:00<00:00, 11.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/10.2M [00:00<?, ? Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   0%|            | 0.00/8.68M [00:00<?, ? Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  29%|▉  | 2.54M/8.68M [00:00<00:00, 12.7M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  47%|█▍ | 4.04M/8.68M [00:00<00:00, 13.7M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  79%|██▎| 6.86M/8.68M [00:00<00:00, 13.9M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:  95%|██▊| 8.27M/8.68M [00:00<00:00, 13.9M Bytes/s]

Get sub-01/s .. t_T1w.nii.gz:   0%|            | 0.00/8.68M [00:00<?, ? Bytes/s]
Total:  10%|██▋                        | 216M/2.17G [00:24<03:41, 8.81M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   0%|             | 0.00/104M [00:00<?, ? Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   1%|    | 1.06M/104M [00:00<00:10, 9.90M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   2%|    | 2.30M/104M [00:00<00:08, 11.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   4%|▏   | 3.68M/104M [00:00<00:08, 12.4M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   6%|▏   | 6.10M/104M [00:00<00:08, 11.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   7%|▎   | 7.68M/104M [00:00<00:09, 9.82M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   9%|▍   | 9.81M/104M [00:01<00:13, 7.10M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  11%|▍   | 11.2M/104M [00:01<00:11, 8.05M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  12%|▍   | 12.7M/104M [00:01<00:09, 9.39M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  15%|▌   | 15.2M/104M [00:01<00:08, 10.2M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  16%|▋   | 16.9M/104M [00:01<00:09, 9.56M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  18%|▋   | 19.2M/104M [00:02<00:08, 10.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  21%|▊   | 21.4M/104M [00:02<00:08, 10.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  23%|▉   | 23.9M/104M [00:02<00:07, 10.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  25%|▉   | 25.6M/104M [00:02<00:07, 9.85M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  27%|█   | 27.8M/104M [00:02<00:07, 10.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  29%|█▏  | 30.2M/104M [00:03<00:07, 10.5M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  31%|█▎  | 32.6M/104M [00:03<00:06, 10.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  34%|█▎  | 35.0M/104M [00:03<00:06, 10.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  36%|█▍  | 37.4M/104M [00:03<00:06, 11.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  38%|█▌  | 40.0M/104M [00:03<00:05, 11.4M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  41%|█▋  | 42.5M/104M [00:04<00:05, 11.5M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  42%|█▋  | 44.2M/104M [00:04<00:05, 10.5M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  43%|█▋  | 45.3M/104M [00:04<00:05, 10.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  45%|█▊  | 46.9M/104M [00:04<00:04, 11.5M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  47%|█▉  | 49.4M/104M [00:04<00:04, 11.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  50%|█▉  | 51.8M/104M [00:04<00:04, 11.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  52%|██  | 54.4M/104M [00:05<00:04, 11.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  54%|██▏ | 56.6M/104M [00:05<00:04, 11.4M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  55%|██▏ | 57.8M/104M [00:05<00:04, 11.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  57%|██▎ | 59.2M/104M [00:05<00:03, 11.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  59%|██▎ | 61.4M/104M [00:05<00:03, 11.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  60%|██▍ | 62.8M/104M [00:05<00:03, 11.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  61%|██▍ | 64.1M/104M [00:05<00:03, 11.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  64%|██▌ | 66.7M/104M [00:06<00:03, 12.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  66%|██▋ | 69.0M/104M [00:06<00:03, 11.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  67%|██▋ | 70.3M/104M [00:06<00:02, 11.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  69%|██▊ | 71.7M/104M [00:06<00:02, 12.2M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  71%|██▊ | 73.9M/104M [00:06<00:02, 11.5M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  72%|██▉ | 75.2M/104M [00:06<00:02, 11.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  75%|██▉ | 77.7M/104M [00:07<00:02, 11.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  76%|███ | 78.9M/104M [00:07<00:02, 11.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  78%|███ | 81.3M/104M [00:07<00:01, 11.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  81%|███▏| 84.0M/104M [00:07<00:01, 11.9M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  83%|███▎| 86.0M/104M [00:07<00:01, 11.1M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  85%|███▍| 88.4M/104M [00:08<00:01, 11.3M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  87%|███▍| 90.4M/104M [00:08<00:01, 10.6M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  89%|███▌| 92.7M/104M [00:08<00:01, 10.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  90%|███▌| 94.0M/104M [00:08<00:00, 11.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  92%|███▋| 95.5M/104M [00:08<00:00, 11.8M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  94%|███▊| 98.0M/104M [00:08<00:00, 11.7M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  97%|████▊| 101M/104M [00:09<00:00, 12.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:  99%|████▉| 103M/104M [00:09<00:00, 12.0M Bytes/s]

Get sub-01/s .. t_dwi.nii.gz:   0%|             | 0.00/104M [00:00<?, ? Bytes/s]
Total:  15%|███▉                       | 320M/2.17G [00:34<03:18, 9.32M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/22.9M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   6%|▏  | 1.47M/22.9M [00:00<00:01, 14.6M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  17%|▌  | 3.95M/22.9M [00:00<00:01, 11.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  24%|▋  | 5.61M/22.9M [00:00<00:01, 12.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  33%|▉  | 7.59M/22.9M [00:00<00:01, 11.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  44%|█▎ | 9.98M/22.9M [00:00<00:01, 11.2M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  54%|█▌ | 12.3M/22.9M [00:01<00:00, 11.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  63%|█▉ | 14.4M/22.9M [00:01<00:00, 10.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  73%|██▏| 16.7M/22.9M [00:01<00:00, 10.7M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  78%|██▎| 17.8M/22.9M [00:01<00:00, 10.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  84%|██▌| 19.2M/22.9M [00:01<00:00, 11.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  89%|██▋| 20.5M/22.9M [00:01<00:00, 11.7M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  98%|██▉| 22.6M/22.9M [00:02<00:00, 11.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/22.9M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/24.5M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   5%|▏  | 1.29M/24.5M [00:00<00:01, 12.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  14%|▍  | 3.32M/24.5M [00:00<00:01, 10.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  19%|▌  | 4.53M/24.5M [00:00<00:01, 11.2M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  27%|▊  | 6.64M/24.5M [00:00<00:01, 10.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  36%|█  | 8.69M/24.5M [00:00<00:01, 10.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  41%|█▏ | 10.1M/24.5M [00:01<00:01, 9.14M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  48%|█▍ | 11.8M/24.5M [00:01<00:01, 8.85M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  55%|█▋ | 13.4M/24.5M [00:01<00:01, 8.53M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  61%|█▊ | 14.9M/24.5M [00:01<00:01, 8.03M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  64%|█▉ | 15.7M/24.5M [00:01<00:01, 8.08M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  70%|██ | 17.1M/24.5M [00:01<00:00, 7.65M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  73%|██▏| 17.9M/24.5M [00:02<00:00, 7.74M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  77%|██▎| 18.9M/24.5M [00:02<00:00, 8.30M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  82%|██▍| 19.9M/24.5M [00:02<00:00, 8.66M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  85%|██▌| 20.9M/24.5M [00:02<00:00, 8.74M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  91%|██▋| 22.3M/24.5M [00:02<00:00, 9.75M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  96%|██▊| 23.4M/24.5M [00:02<00:00, 10.0M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/24.5M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/31.6M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   4%|▏  | 1.41M/31.6M [00:00<00:02, 14.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  13%|▍  | 4.12M/31.6M [00:00<00:02, 10.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  17%|▌  | 5.50M/31.6M [00:00<00:02, 11.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  24%|▋  | 7.64M/31.6M [00:00<00:02, 10.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  32%|▉  | 9.99M/31.6M [00:00<00:01, 10.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  39%|█▏ | 12.4M/31.6M [00:01<00:01, 11.2M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  45%|█▎ | 14.3M/31.6M [00:01<00:01, 10.4M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  49%|█▍ | 15.6M/31.6M [00:01<00:01, 10.7M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  55%|█▋ | 17.4M/31.6M [00:01<00:01, 12.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  61%|█▊ | 19.2M/31.6M [00:01<00:01, 10.9M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  65%|█▉ | 20.6M/31.6M [00:01<00:00, 11.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  71%|██▏| 22.4M/31.6M [00:01<00:00, 12.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  77%|██▎| 24.4M/31.6M [00:02<00:00, 11.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  84%|██▌| 26.7M/31.6M [00:02<00:00, 11.2M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  89%|██▋| 28.0M/31.6M [00:02<00:00, 11.6M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  94%|██▊| 29.9M/31.6M [00:02<00:00, 13.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/31.6M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/12.0M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:  23%|▋  | 2.81M/12.0M [00:00<00:00, 13.3M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  35%|█  | 4.18M/12.0M [00:00<00:00, 13.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  49%|█▍ | 5.94M/12.0M [00:00<00:00, 10.6M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  70%|██ | 8.43M/12.0M [00:00<00:00, 11.1M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  84%|██▌| 10.1M/12.0M [00:00<00:00, 9.98M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/12.0M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/10.4M [00:00<?, ? Bytes/s]

Get sub-01/s .. _bold.nii.gz:  28%|▊  | 2.86M/10.4M [00:00<00:00, 13.8M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  51%|█▌ | 5.26M/10.4M [00:00<00:00, 12.7M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  74%|██▏| 7.69M/10.4M [00:00<00:00, 11.5M Bytes/s]

Get sub-01/s .. _bold.nii.gz:  98%|██▉| 10.2M/10.4M [00:00<00:00, 11.6M Bytes/s]

Get sub-01/s .. _bold.nii.gz:   0%|            | 0.00/10.4M [00:00<?, ? Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:   0%|            | 0.00/8.90M [00:00<?, ? Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  13%|▍  | 1.14M/8.90M [00:00<00:00, 11.4M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  30%|▉  | 2.67M/8.90M [00:00<00:00, 13.6M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  45%|█▎ | 4.04M/8.90M [00:00<00:00, 13.6M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  67%|██ | 5.98M/8.90M [00:00<00:00, 10.7M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  94%|██▊| 8.36M/8.90M [00:00<00:00, 11.0M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:   0%|            | 0.00/8.90M [00:00<?, ? Bytes/s]
Total:  20%|█████▎                     | 430M/2.17G [00:46<03:08, 9.24M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   0%|             | 0.00/101M [00:00<?, ? Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   3%|    | 2.78M/101M [00:00<00:07, 13.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   5%|▏   | 4.96M/101M [00:00<00:08, 11.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   6%|▎   | 6.39M/101M [00:00<00:07, 12.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   8%|▎   | 8.52M/101M [00:00<00:08, 11.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  10%|▍   | 9.98M/101M [00:00<00:07, 11.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  12%|▍   | 12.3M/101M [00:01<00:07, 11.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  14%|▌   | 14.6M/101M [00:01<00:07, 11.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  16%|▋   | 16.2M/101M [00:01<00:07, 12.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  18%|▋   | 18.6M/101M [00:01<00:06, 11.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  21%|▊   | 21.1M/101M [00:01<00:06, 11.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  23%|▉   | 23.5M/101M [00:01<00:06, 11.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  26%|█   | 26.0M/101M [00:02<00:06, 11.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  28%|█▏  | 28.6M/101M [00:02<00:06, 12.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  31%|█▏  | 31.3M/101M [00:02<00:05, 12.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  33%|█▎  | 33.5M/101M [00:02<00:05, 11.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  35%|█▍  | 35.3M/101M [00:02<00:05, 12.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  37%|█▍  | 37.7M/101M [00:03<00:05, 12.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  40%|█▌  | 40.2M/101M [00:03<00:05, 12.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  41%|█▋  | 41.6M/101M [00:03<00:04, 12.5M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  44%|█▊  | 44.4M/101M [00:03<00:04, 12.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  46%|█▊  | 47.1M/101M [00:03<00:04, 12.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  49%|█▉  | 49.5M/101M [00:04<00:04, 12.5M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  50%|██  | 50.9M/101M [00:04<00:04, 12.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  52%|██  | 52.4M/101M [00:04<00:03, 12.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  53%|██  | 53.7M/101M [00:04<00:03, 12.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  54%|██▏ | 55.0M/101M [00:04<00:03, 12.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  56%|██▏ | 56.5M/101M [00:04<00:03, 12.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  58%|██▎ | 59.1M/101M [00:04<00:03, 12.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  60%|██▍ | 60.4M/101M [00:04<00:03, 12.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  61%|██▍ | 61.8M/101M [00:05<00:03, 12.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  62%|██▍ | 63.2M/101M [00:05<00:02, 12.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  64%|██▌ | 64.6M/101M [00:05<00:02, 12.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  65%|██▌ | 65.9M/101M [00:05<00:02, 13.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  66%|██▋ | 67.3M/101M [00:05<00:02, 12.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  68%|██▋ | 68.6M/101M [00:05<00:02, 12.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  69%|██▊ | 70.1M/101M [00:05<00:02, 13.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  72%|██▊ | 72.5M/101M [00:05<00:02, 12.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  73%|██▉ | 74.0M/101M [00:05<00:02, 13.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  74%|██▉ | 75.3M/101M [00:06<00:02, 12.5M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  76%|███ | 76.7M/101M [00:06<00:01, 13.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  77%|███ | 78.2M/101M [00:06<00:01, 13.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  79%|███▏| 79.6M/101M [00:06<00:01, 13.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  81%|███▏| 82.3M/101M [00:06<00:01, 13.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  83%|███▎| 83.7M/101M [00:06<00:01, 13.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  84%|███▎| 85.1M/101M [00:06<00:01, 13.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  87%|███▍| 87.9M/101M [00:07<00:01, 13.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  89%|███▌| 90.4M/101M [00:07<00:00, 12.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  92%|███▋| 92.7M/101M [00:07<00:00, 12.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  93%|███▋| 94.0M/101M [00:07<00:00, 12.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  94%|███▊| 95.4M/101M [00:07<00:00, 12.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  95%|███▊| 96.7M/101M [00:07<00:00, 12.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  97%|███▊| 98.1M/101M [00:07<00:00, 12.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  99%|████▉| 101M/101M [00:08<00:00, 12.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   0%|             | 0.00/101M [00:00<?, ? Bytes/s]

Total:  24%|██████▌                    | 532M/2.17G [00:55<02:50, 9.64M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/22.7M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   6%|▏  | 1.42M/22.7M [00:00<00:01, 14.2M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  19%|▌  | 4.30M/22.7M [00:00<00:01, 14.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  28%|▊  | 6.36M/22.7M [00:00<00:01, 11.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  39%|█▏ | 8.77M/22.7M [00:00<00:01, 11.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  47%|█▍ | 10.8M/22.7M [00:00<00:01, 10.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  57%|█▋ | 13.0M/22.7M [00:01<00:00, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  62%|█▊ | 14.1M/22.7M [00:01<00:00, 10.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  69%|██ | 15.6M/22.7M [00:01<00:00, 11.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  77%|██▎| 17.5M/22.7M [00:01<00:00, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  83%|██▍| 18.9M/22.7M [00:01<00:00, 11.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  90%|██▋| 20.4M/22.7M [00:01<00:00, 11.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  99%|██▉| 22.6M/22.7M [00:02<00:00, 11.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/22.7M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/24.4M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:  13%|▍  | 3.14M/24.4M [00:00<00:01, 14.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  26%|▊  | 6.35M/24.4M [00:00<00:01, 13.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  34%|█  | 8.19M/24.4M [00:00<00:01, 11.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  43%|█▎ | 10.5M/24.4M [00:00<00:01, 11.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  51%|█▌ | 12.5M/24.4M [00:01<00:01, 10.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  56%|█▋ | 13.6M/24.4M [00:01<00:01, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  62%|█▊ | 15.0M/24.4M [00:01<00:00, 11.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  70%|██ | 17.0M/24.4M [00:01<00:00, 10.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  81%|██▍| 19.8M/24.4M [00:01<00:00, 11.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  89%|██▋| 21.8M/24.4M [00:01<00:00, 10.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  95%|██▊| 23.1M/24.4M [00:02<00:00, 11.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/24.4M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/31.2M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   8%|▎  | 2.63M/31.2M [00:00<00:02, 13.2M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  13%|▍  | 4.09M/31.2M [00:00<00:01, 13.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  20%|▌  | 6.26M/31.2M [00:00<00:02, 11.2M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  24%|▋  | 7.48M/31.2M [00:00<00:02, 11.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  31%|▉  | 9.64M/31.2M [00:00<00:01, 10.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  35%|█  | 10.8M/31.2M [00:00<00:01, 10.9M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  42%|█▏ | 13.0M/31.2M [00:01<00:01, 10.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  47%|█▍ | 14.7M/31.2M [00:01<00:01, 12.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  54%|█▌ | 16.9M/31.2M [00:01<00:01, 11.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  63%|█▉ | 19.6M/31.2M [00:01<00:00, 11.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  70%|██ | 22.0M/31.2M [00:01<00:00, 11.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  79%|██▎| 24.7M/31.2M [00:02<00:00, 12.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  87%|██▌| 27.2M/31.2M [00:02<00:00, 11.9M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  96%|██▊| 29.9M/31.2M [00:02<00:00, 12.2M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/31.2M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/12.0M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:  13%|▍  | 1.51M/12.0M [00:00<00:00, 15.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  26%|▊  | 3.14M/12.0M [00:00<00:00, 15.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  39%|█▏ | 4.67M/12.0M [00:00<00:00, 10.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  52%|█▌ | 6.30M/12.0M [00:00<00:00, 12.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  71%|██▏| 8.61M/12.0M [00:00<00:00, 11.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  89%|██▋| 10.8M/12.0M [00:00<00:00, 11.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/12.0M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/10.4M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:  12%|▎  | 1.28M/10.4M [00:00<00:00, 12.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  27%|▊  | 2.81M/10.4M [00:00<00:00, 14.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  51%|█▌ | 5.26M/10.4M [00:00<00:00, 12.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  71%|██▏| 7.37M/10.4M [00:00<00:00, 11.2M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  86%|██▌| 8.88M/10.4M [00:00<00:00, 11.9M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/10.4M [00:00<?, ? Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:   0%|            | 0.00/10.0M [00:00<?, ? Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  28%|▊  | 2.78M/10.0M [00:00<00:00, 13.9M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  42%|█▎ | 4.24M/10.0M [00:00<00:00, 14.2M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  65%|█▉ | 6.53M/10.0M [00:00<00:00, 11.9M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:  89%|██▋| 8.96M/10.0M [00:00<00:00, 11.7M Bytes/s]

Get sub-02/s .. t_T1w.nii.gz:   0%|            | 0.00/10.0M [00:00<?, ? Bytes/s]

Total:  30%|███████▉                   | 643M/2.17G [01:07<02:39, 9.57M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   0%|             | 0.00/104M [00:00<?, ? Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   3%|    | 3.14M/104M [00:00<00:06, 14.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   5%|▏   | 5.57M/104M [00:00<00:07, 12.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   7%|▎   | 7.57M/104M [00:00<00:08, 11.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   9%|▎   | 9.02M/104M [00:00<00:07, 12.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  11%|▍   | 11.1M/104M [00:00<00:08, 11.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  13%|▌   | 13.6M/104M [00:01<00:08, 11.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  15%|▌   | 15.6M/104M [00:01<00:08, 10.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  17%|▋   | 17.9M/104M [00:01<00:07, 10.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  19%|▊   | 19.9M/104M [00:01<00:08, 10.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  20%|▊   | 21.1M/104M [00:01<00:07, 10.5M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  22%|▉   | 22.9M/104M [00:02<00:06, 12.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  24%|▉   | 24.8M/104M [00:02<00:07, 10.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  26%|█   | 27.5M/104M [00:02<00:06, 11.5M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  28%|█   | 29.1M/104M [00:02<00:07, 10.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  30%|█▏  | 31.7M/104M [00:02<00:06, 11.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  33%|█▎  | 34.0M/104M [00:03<00:06, 10.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  35%|█▍  | 36.6M/104M [00:03<00:05, 11.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  37%|█▍  | 38.3M/104M [00:03<00:06, 10.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  38%|█▌  | 39.6M/104M [00:03<00:06, 10.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  39%|█▌  | 41.0M/104M [00:03<00:05, 11.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  41%|█▋  | 43.1M/104M [00:03<00:05, 11.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  44%|█▊  | 45.7M/104M [00:04<00:05, 11.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  46%|█▊  | 47.6M/104M [00:04<00:05, 11.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  47%|█▊  | 48.8M/104M [00:04<00:05, 11.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  48%|█▉  | 50.4M/104M [00:04<00:04, 11.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  50%|██  | 52.4M/104M [00:04<00:04, 11.0M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  51%|██  | 53.7M/104M [00:04<00:04, 11.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  53%|██  | 55.1M/104M [00:04<00:04, 11.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  55%|██▏ | 57.2M/104M [00:05<00:04, 11.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  56%|██▎ | 58.7M/104M [00:05<00:03, 11.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  58%|██▎ | 60.1M/104M [00:05<00:03, 12.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  60%|██▍ | 62.6M/104M [00:05<00:03, 12.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  62%|██▍ | 64.8M/104M [00:05<00:03, 11.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  64%|██▌ | 66.3M/104M [00:05<00:03, 12.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  66%|██▋ | 68.7M/104M [00:06<00:02, 12.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  67%|██▋ | 70.3M/104M [00:06<00:02, 13.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  70%|██▊ | 72.6M/104M [00:06<00:02, 12.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  71%|██▊ | 73.9M/104M [00:06<00:02, 12.1M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  72%|██▉ | 75.4M/104M [00:06<00:02, 12.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  74%|██▉ | 77.0M/104M [00:06<00:02, 11.7M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  76%|███ | 79.0M/104M [00:06<00:01, 13.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  78%|███ | 81.1M/104M [00:07<00:01, 12.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  79%|███▏| 82.5M/104M [00:07<00:01, 12.5M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  81%|███▏| 84.7M/104M [00:07<00:01, 11.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  83%|███▎| 86.2M/104M [00:07<00:01, 12.2M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  85%|███▍| 89.0M/104M [00:07<00:01, 12.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  87%|███▍| 91.2M/104M [00:07<00:01, 11.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  89%|███▌| 92.5M/104M [00:07<00:01, 11.8M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  90%|███▌| 93.9M/104M [00:08<00:00, 12.4M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  92%|███▋| 96.1M/104M [00:08<00:00, 11.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  94%|███▊| 97.7M/104M [00:08<00:00, 12.5M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  96%|████▊| 100M/104M [00:08<00:00, 11.9M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:  98%|████▉| 102M/104M [00:08<00:00, 12.6M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz: 100%|████▉| 104M/104M [00:08<00:00, 12.3M Bytes/s]

Get sub-02/s .. t_dwi.nii.gz:   0%|             | 0.00/104M [00:00<?, ? Bytes/s]

Total:  34%|█████████▎                 | 747M/2.17G [01:16<02:26, 9.75M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/23.3M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:  13%|▍  | 3.10M/23.3M [00:00<00:01, 15.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  22%|▋  | 5.09M/23.3M [00:00<00:01, 11.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  29%|▊  | 6.72M/23.3M [00:00<00:01, 12.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  38%|█▏ | 8.94M/23.3M [00:00<00:01, 11.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  48%|█▍ | 11.2M/23.3M [00:00<00:01, 11.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  56%|█▋ | 13.2M/23.3M [00:01<00:00, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  66%|█▉ | 15.3M/23.3M [00:01<00:00, 10.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  74%|██▏| 17.3M/23.3M [00:01<00:00, 10.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  84%|██▌| 19.6M/23.3M [00:01<00:00, 10.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  93%|██▊| 21.8M/23.3M [00:02<00:00, 10.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/23.3M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/24.9M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:  13%|▍  | 3.14M/24.9M [00:00<00:01, 14.8M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  21%|▋  | 5.28M/24.9M [00:00<00:01, 11.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  32%|▉  | 7.85M/24.9M [00:00<00:01, 12.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  40%|█▏ | 9.90M/24.9M [00:00<00:01, 11.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  44%|█▎ | 11.0M/24.9M [00:00<00:01, 11.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  55%|█▋ | 13.6M/24.9M [00:01<00:00, 11.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  65%|█▉ | 16.1M/24.9M [00:01<00:00, 11.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  74%|██▏| 18.4M/24.9M [00:01<00:00, 11.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  84%|██▌| 20.9M/24.9M [00:01<00:00, 11.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  95%|██▊| 23.7M/24.9M [00:02<00:00, 12.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/24.9M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/32.2M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   4%|   | 1.33M/32.2M [00:00<00:02, 13.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  13%|▍  | 4.25M/32.2M [00:00<00:02, 12.9M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  20%|▌  | 6.33M/32.2M [00:00<00:02, 11.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  27%|▊  | 8.59M/32.2M [00:00<00:02, 11.1M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  30%|▉  | 9.74M/32.2M [00:00<00:02, 11.2M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  36%|█  | 11.8M/32.2M [00:01<00:01, 10.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  44%|█▎ | 14.1M/32.2M [00:01<00:01, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  47%|█▍ | 15.2M/32.2M [00:01<00:01, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  54%|█▌ | 17.4M/32.2M [00:01<00:01, 10.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  57%|█▋ | 18.4M/32.2M [00:01<00:01, 10.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  60%|█▊ | 19.5M/32.2M [00:01<00:01, 10.3M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  64%|█▉ | 20.7M/32.2M [00:01<00:01, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  70%|██ | 22.7M/32.2M [00:02<00:00, 10.2M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  75%|██▏| 24.0M/32.2M [00:02<00:00, 10.7M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  81%|██▍| 26.1M/32.2M [00:02<00:00, 10.4M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  88%|██▋| 28.3M/32.2M [00:02<00:00, 10.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  95%|██▊| 30.6M/32.2M [00:02<00:00, 10.5M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/32.2M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/12.3M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:  20%|▌  | 2.41M/12.3M [00:00<00:00, 12.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  37%|█  | 4.54M/12.3M [00:00<00:00, 10.6M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  46%|█▍ | 5.74M/12.3M [00:00<00:00, 11.0M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  61%|█▊ | 7.59M/12.3M [00:00<00:00, 9.93M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  73%|██▏| 9.06M/12.3M [00:01<00:00, 6.27M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  80%|██▍| 9.93M/12.3M [00:01<00:00, 6.54M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  90%|██▋| 11.1M/12.3M [00:01<00:00, 7.52M Bytes/s]

Get sub-02/s .. _bold.nii.gz: 100%|██▉| 12.3M/12.3M [00:01<00:00, 8.23M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/12.3M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/10.5M [00:00<?, ? Bytes/s]

Get sub-02/s .. _bold.nii.gz:  17%|▌  | 1.80M/10.5M [00:00<00:00, 8.95M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  28%|▊  | 2.89M/10.5M [00:00<00:01, 6.85M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  37%|█  | 3.88M/10.5M [00:00<00:01, 5.93M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  46%|█▎ | 4.79M/10.5M [00:00<00:01, 5.34M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  52%|█▌ | 5.43M/10.5M [00:00<00:00, 5.53M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  57%|█▋ | 6.02M/10.5M [00:01<00:00, 5.61M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  64%|█▉ | 6.75M/10.5M [00:01<00:00, 6.04M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  71%|██▏| 7.46M/10.5M [00:01<00:00, 6.28M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  77%|██▎| 8.13M/10.5M [00:01<00:00, 6.38M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  84%|██▌| 8.80M/10.5M [00:01<00:00, 6.41M Bytes/s]

Get sub-02/s .. _bold.nii.gz:  97%|██▉| 10.2M/10.5M [00:01<00:00, 6.58M Bytes/s]

Get sub-02/s .. _bold.nii.gz:   0%|            | 0.00/10.5M [00:00<?, ? Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:   0%|            | 0.00/9.51M [00:00<?, ? Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  15%|▍  | 1.40M/9.51M [00:00<00:00, 14.0M Bytes/s]

Total:  39%|██████████▌                | 850M/2.17G [01:30<02:19, 9.44M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  41%|█▏ | 3.88M/9.51M [00:00<00:00, 6.99M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  51%|█▌ | 4.89M/9.51M [00:00<00:00, 7.53M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  68%|██ | 6.50M/9.51M [00:00<00:00, 9.55M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  89%|██▋| 8.50M/9.51M [00:00<00:00, 9.47M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:   0%|            | 0.00/9.51M [00:00<?, ? Bytes/s]
Total:  40%|██████████▋                | 860M/2.17G [01:30<02:18, 9.49M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   0%|             | 0.00/104M [00:00<?, ? Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   1%|    | 1.45M/104M [00:00<00:07, 14.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   4%|▏   | 3.84M/104M [00:00<00:09, 10.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   5%|▏   | 5.28M/104M [00:00<00:08, 11.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   7%|▎   | 7.49M/104M [00:00<00:08, 11.3M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   9%|▍   | 9.83M/104M [00:00<00:08, 11.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  12%|▍   | 12.2M/104M [00:01<00:08, 11.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  13%|▌   | 13.3M/104M [00:01<00:08, 11.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  14%|▌   | 14.6M/104M [00:01<00:07, 11.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  15%|▌   | 15.9M/104M [00:01<00:07, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  18%|▋   | 18.3M/104M [00:01<00:07, 11.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  19%|▋   | 19.5M/104M [00:01<00:07, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  20%|▊   | 20.7M/104M [00:01<00:07, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  22%|▉   | 23.4M/104M [00:02<00:06, 11.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  25%|▉   | 25.7M/104M [00:02<00:06, 11.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  26%|█   | 26.9M/104M [00:02<00:06, 11.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  28%|█▏  | 29.3M/104M [00:02<00:06, 11.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  29%|█▏  | 30.6M/104M [00:02<00:06, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  31%|█▏  | 31.7M/104M [00:02<00:06, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  33%|█▎  | 34.2M/104M [00:02<00:06, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  34%|█▎  | 35.4M/104M [00:03<00:05, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  35%|█▍  | 36.6M/104M [00:03<00:05, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  36%|█▍  | 37.8M/104M [00:03<00:05, 11.3M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  38%|█▌  | 39.3M/104M [00:03<00:05, 12.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  40%|█▌  | 41.7M/104M [00:03<00:05, 12.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  43%|█▋  | 44.4M/104M [00:03<00:04, 12.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  45%|█▊  | 46.7M/104M [00:04<00:04, 11.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  46%|█▊  | 47.9M/104M [00:04<00:04, 11.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  47%|█▉  | 49.4M/104M [00:04<00:04, 12.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  50%|█▉  | 51.7M/104M [00:04<00:04, 11.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  52%|██  | 54.4M/104M [00:04<00:05, 9.18M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  54%|██▏ | 56.3M/104M [00:05<00:05, 8.86M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  55%|██▏ | 57.3M/104M [00:05<00:05, 9.04M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  56%|██▏ | 58.3M/104M [00:05<00:05, 9.02M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  57%|██▎ | 59.3M/104M [00:05<00:04, 9.25M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  58%|██▎ | 60.3M/104M [00:05<00:04, 9.22M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  59%|██▎ | 61.3M/104M [00:05<00:04, 9.33M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  60%|██▍ | 62.4M/104M [00:05<00:04, 9.51M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  61%|██▍ | 63.4M/104M [00:05<00:04, 9.57M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  62%|██▍ | 64.4M/104M [00:05<00:04, 9.75M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  63%|██▌ | 65.5M/104M [00:06<00:03, 9.70M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  64%|██▌ | 66.6M/104M [00:06<00:03, 9.96M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  65%|██▌ | 67.6M/104M [00:06<00:03, 9.90M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  66%|██▋ | 68.7M/104M [00:06<00:03, 10.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  67%|██▋ | 69.7M/104M [00:06<00:03, 10.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  68%|██▋ | 70.8M/104M [00:06<00:03, 10.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  70%|██▊ | 73.0M/104M [00:06<00:03, 10.3M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  71%|██▊ | 74.1M/104M [00:06<00:02, 10.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  72%|██▉ | 75.2M/104M [00:06<00:02, 10.3M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  73%|██▉ | 76.3M/104M [00:07<00:02, 10.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  74%|██▉ | 77.4M/104M [00:07<00:02, 10.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  75%|███ | 78.5M/104M [00:07<00:02, 10.3M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  77%|███ | 79.6M/104M [00:07<00:02, 10.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  78%|███ | 80.7M/104M [00:07<00:02, 10.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  79%|███▏| 81.9M/104M [00:07<00:02, 10.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  80%|███▏| 83.0M/104M [00:07<00:02, 10.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  81%|███▏| 84.1M/104M [00:07<00:01, 10.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  82%|███▎| 85.2M/104M [00:07<00:01, 10.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  83%|███▎| 86.4M/104M [00:08<00:01, 10.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  84%|███▎| 87.5M/104M [00:08<00:01, 10.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  85%|███▍| 88.7M/104M [00:08<00:01, 10.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  86%|███▍| 89.8M/104M [00:08<00:01, 10.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  87%|███▍| 91.0M/104M [00:08<00:01, 10.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  89%|███▌| 92.1M/104M [00:08<00:01, 10.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  90%|███▌| 93.2M/104M [00:08<00:00, 10.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  91%|███▋| 94.4M/104M [00:08<00:00, 10.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  92%|███▋| 95.6M/104M [00:08<00:00, 11.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  93%|███▋| 96.7M/104M [00:08<00:00, 10.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  94%|███▊| 97.9M/104M [00:09<00:00, 11.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  95%|███▊| 99.0M/104M [00:09<00:00, 10.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  96%|████▊| 100M/104M [00:09<00:00, 11.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  97%|████▊| 101M/104M [00:09<00:00, 11.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  99%|████▉| 103M/104M [00:09<00:00, 11.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz: 100%|████▉| 104M/104M [00:09<00:00, 11.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   0%|             | 0.00/104M [00:00<?, ? Bytes/s]

Total:  44%|███████████▉               | 964M/2.17G [01:40<02:06, 9.57M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/24.2M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:  10%|▎  | 2.31M/24.2M [00:00<00:01, 12.2M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  17%|▌  | 4.08M/24.2M [00:00<00:02, 9.84M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  25%|▊  | 6.11M/24.2M [00:00<00:01, 12.9M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  34%|█  | 8.16M/24.2M [00:00<00:01, 9.16M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  43%|█▎ | 10.4M/24.2M [00:01<00:01, 9.62M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  51%|█▌ | 12.4M/24.2M [00:01<00:01, 9.56M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  59%|█▊ | 14.3M/24.2M [00:01<00:01, 9.48M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  68%|██ | 16.4M/24.2M [00:01<00:00, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  73%|██▏| 17.6M/24.2M [00:01<00:00, 10.7M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  82%|██▍| 20.0M/24.2M [00:01<00:00, 10.0M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  91%|██▋| 22.0M/24.2M [00:02<00:00, 9.84M Bytes/s]

Get sub-05/s .. _bold.nii.gz: 100%|██▉| 24.2M/24.2M [00:02<00:00, 9.97M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/24.2M [00:00<?, ? Bytes/s]
Total:  45%|████████████▎              | 988M/2.17G [01:43<02:04, 9.54M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/26.0M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   9%|▎  | 2.38M/26.0M [00:00<00:02, 11.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  14%|▍  | 3.71M/26.0M [00:00<00:01, 12.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  22%|▋  | 5.66M/26.0M [00:00<00:01, 10.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  30%|▉  | 7.89M/26.0M [00:00<00:01, 10.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  38%|█▏ | 9.92M/26.0M [00:00<00:01, 10.2M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  46%|█▍ | 12.1M/26.0M [00:01<00:01, 10.2M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  54%|█▌ | 14.0M/26.0M [00:01<00:01, 9.87M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  62%|█▊ | 16.2M/26.0M [00:01<00:00, 10.0M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  69%|██ | 18.0M/26.0M [00:01<00:00, 9.53M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  78%|██▎| 20.2M/26.0M [00:01<00:00, 9.81M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  85%|██▌| 22.2M/26.0M [00:02<00:00, 9.70M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  93%|██▊| 24.1M/26.0M [00:02<00:00, 9.60M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/26.0M [00:00<?, ? Bytes/s]
Total:  47%|████████████▏             | 1.01G/2.17G [01:46<02:01, 9.52M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/33.6M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   7%|▏  | 2.39M/33.6M [00:00<00:02, 11.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  13%|▍  | 4.32M/33.6M [00:00<00:02, 10.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  17%|▌  | 5.82M/33.6M [00:00<00:02, 11.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  23%|▋  | 7.72M/33.6M [00:00<00:02, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  29%|▊  | 9.78M/33.6M [00:00<00:02, 10.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  37%|█  | 12.5M/33.6M [00:01<00:01, 11.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  41%|█▏ | 13.8M/33.6M [00:01<00:02, 9.49M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  45%|█▎ | 15.0M/33.6M [00:01<00:01, 9.61M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  49%|█▍ | 16.5M/33.6M [00:01<00:01, 10.8M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  56%|█▋ | 18.6M/33.6M [00:01<00:01, 10.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  63%|█▉ | 21.0M/33.6M [00:01<00:01, 10.9M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  69%|██ | 23.2M/33.6M [00:02<00:00, 10.7M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  75%|██▎| 25.3M/33.6M [00:02<00:00, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  82%|██▍| 27.6M/33.6M [00:02<00:00, 10.7M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  89%|██▋| 29.8M/33.6M [00:02<00:00, 10.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  95%|██▊| 31.8M/33.6M [00:03<00:00, 10.2M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/33.6M [00:00<?, ? Bytes/s]
Total:  48%|████████████▌             | 1.05G/2.17G [01:50<01:58, 9.51M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/12.9M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:  19%|▌  | 2.43M/12.9M [00:00<00:00, 11.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  32%|▉  | 4.19M/12.9M [00:00<00:00, 9.70M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  48%|█▍ | 6.26M/12.9M [00:00<00:00, 12.8M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  65%|█▉ | 8.35M/12.9M [00:00<00:00, 9.23M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  77%|██▎| 9.94M/12.9M [00:00<00:00, 10.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  93%|██▊| 12.1M/12.9M [00:01<00:00, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/12.9M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/11.1M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:  13%|▍  | 1.43M/11.1M [00:00<00:00, 14.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  32%|▉  | 3.56M/11.1M [00:00<00:00, 11.2M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  51%|█▌ | 5.68M/11.1M [00:00<00:00, 10.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  71%|██▏| 7.93M/11.1M [00:00<00:00, 10.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  89%|██▋| 9.88M/11.1M [00:00<00:00, 10.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/11.1M [00:00<?, ? Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:   0%|            | 0.00/9.94M [00:00<?, ? Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  14%|▍  | 1.36M/9.94M [00:00<00:00, 13.4M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  41%|█▏ | 4.04M/9.94M [00:00<00:00, 13.0M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  58%|█▋ | 5.74M/9.94M [00:00<00:00, 10.4M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:  81%|██▍| 8.04M/9.94M [00:00<00:00, 10.6M Bytes/s]

Get sub-05/s .. t_T1w.nii.gz:   0%|            | 0.00/9.94M [00:00<?, ? Bytes/s]
Total:  50%|████████████▉             | 1.08G/2.17G [01:54<01:55, 9.44M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   0%|             | 0.00/108M [00:00<?, ? Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   2%|    | 2.52M/108M [00:00<00:08, 12.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   4%|▏   | 4.16M/108M [00:00<00:07, 13.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   5%|▏   | 5.70M/108M [00:00<00:10, 10.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   7%|▎   | 8.06M/108M [00:00<00:09, 10.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   9%|▎   | 9.84M/108M [00:00<00:10, 9.77M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  11%|▍   | 12.0M/108M [00:01<00:09, 9.99M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  13%|▌   | 14.4M/108M [00:01<00:09, 10.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  15%|▌   | 16.6M/108M [00:01<00:08, 10.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  17%|▋   | 18.8M/108M [00:01<00:08, 10.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  20%|▊   | 21.1M/108M [00:01<00:08, 10.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  22%|▊   | 23.3M/108M [00:02<00:08, 10.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  24%|▉   | 25.4M/108M [00:02<00:07, 10.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  26%|█   | 27.7M/108M [00:02<00:07, 10.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  28%|█   | 30.0M/108M [00:02<00:07, 10.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  30%|█▏  | 32.2M/108M [00:03<00:07, 10.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  32%|█▎  | 34.5M/108M [00:03<00:06, 10.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  34%|█▎  | 37.0M/108M [00:03<00:06, 11.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  36%|█▍  | 39.2M/108M [00:03<00:06, 10.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  37%|█▍  | 40.5M/108M [00:03<00:06, 11.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  39%|█▌  | 42.1M/108M [00:03<00:05, 11.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  41%|█▋  | 44.4M/108M [00:04<00:05, 11.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  44%|█▋  | 47.1M/108M [00:04<00:05, 12.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  46%|█▊  | 49.5M/108M [00:04<00:04, 11.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  48%|█▉  | 52.1M/108M [00:04<00:04, 11.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  50%|██  | 54.5M/108M [00:04<00:04, 11.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  52%|██  | 55.7M/108M [00:05<00:04, 11.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  53%|██▏ | 57.6M/108M [00:05<00:03, 13.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  55%|██▏ | 59.8M/108M [00:05<00:03, 12.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  58%|██▎ | 62.7M/108M [00:05<00:03, 12.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  60%|██▍ | 65.3M/108M [00:05<00:03, 12.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  63%|██▌ | 68.2M/108M [00:06<00:03, 12.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  66%|██▌ | 70.9M/108M [00:06<00:02, 12.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  68%|██▋ | 73.4M/108M [00:06<00:02, 12.6M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  70%|██▊ | 76.1M/108M [00:06<00:02, 12.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  73%|██▉ | 78.8M/108M [00:06<00:02, 12.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  76%|███ | 81.6M/108M [00:07<00:02, 12.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  78%|███ | 83.8M/108M [00:07<00:02, 12.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  79%|███▏| 85.1M/108M [00:07<00:01, 12.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  80%|███▏| 86.6M/108M [00:07<00:01, 12.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  82%|███▎| 89.0M/108M [00:07<00:01, 12.1M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  85%|███▍| 91.7M/108M [00:07<00:01, 12.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  87%|███▍| 93.6M/108M [00:08<00:01, 11.3M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  88%|███▌| 95.0M/108M [00:08<00:01, 11.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  90%|███▌| 97.0M/108M [00:08<00:01, 10.7M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  91%|███▋| 98.5M/108M [00:08<00:00, 11.5M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  92%|███▋| 99.8M/108M [00:08<00:00, 11.8M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  94%|████▋| 101M/108M [00:08<00:00, 12.2M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  96%|████▊| 104M/108M [00:08<00:00, 12.4M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  98%|████▉| 106M/108M [00:09<00:00, 11.9M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:  99%|████▉| 107M/108M [00:09<00:00, 12.0M Bytes/s]

Get sub-05/s .. t_dwi.nii.gz:   0%|             | 0.00/108M [00:00<?, ? Bytes/s]
Total:  55%|██████████████▏           | 1.19G/2.17G [02:04<01:42, 9.57M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/24.9M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:  11%|▎  | 2.71M/24.9M [00:00<00:01, 13.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  17%|▌  | 4.22M/24.9M [00:00<00:01, 14.0M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  27%|▊  | 6.61M/24.9M [00:00<00:01, 10.0M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  31%|▉  | 7.77M/24.9M [00:00<00:01, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  36%|█  | 8.93M/24.9M [00:00<00:01, 10.7M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  42%|█▎ | 10.4M/24.9M [00:00<00:01, 11.8M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  48%|█▍ | 12.0M/24.9M [00:01<00:01, 10.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  53%|█▌ | 13.2M/24.9M [00:01<00:01, 10.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  59%|█▊ | 14.6M/24.9M [00:01<00:00, 11.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  64%|█▉ | 16.1M/24.9M [00:01<00:00, 9.37M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  70%|██ | 17.5M/24.9M [00:01<00:00, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  76%|██▎| 18.9M/24.9M [00:01<00:00, 11.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  87%|██▌| 21.6M/24.9M [00:01<00:00, 11.9M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  96%|██▊| 23.8M/24.9M [00:02<00:00, 11.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/24.9M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/26.7M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   8%|▏  | 2.18M/26.7M [00:00<00:02, 10.9M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  14%|▍  | 3.62M/26.7M [00:00<00:01, 12.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  23%|▋  | 6.26M/26.7M [00:00<00:01, 12.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  31%|▉  | 8.36M/26.7M [00:00<00:01, 11.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  39%|█▏ | 10.3M/26.7M [00:00<00:01, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  48%|█▍ | 12.7M/26.7M [00:01<00:01, 10.8M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  56%|█▋ | 15.1M/26.7M [00:01<00:01, 10.9M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  66%|█▉ | 17.7M/26.7M [00:01<00:00, 11.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  76%|██▎| 20.4M/26.7M [00:01<00:00, 11.9M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  83%|██▍| 22.1M/26.7M [00:02<00:00, 10.7M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  87%|██▌| 23.3M/26.7M [00:02<00:00, 10.7M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  93%|██▊| 24.8M/26.7M [00:02<00:00, 11.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/26.7M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/34.4M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   9%|▎  | 3.14M/34.4M [00:00<00:02, 15.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  19%|▌  | 6.54M/34.4M [00:00<00:02, 13.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  26%|▊  | 8.95M/34.4M [00:00<00:02, 12.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  32%|▉  | 10.9M/34.4M [00:00<00:02, 11.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  37%|█  | 12.7M/34.4M [00:01<00:02, 10.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  40%|█▏ | 13.9M/34.4M [00:01<00:01, 10.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  44%|█▎ | 15.2M/34.4M [00:01<00:01, 10.9M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  49%|█▍ | 17.0M/34.4M [00:01<00:01, 9.92M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  56%|█▋ | 19.1M/34.4M [00:01<00:01, 10.2M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  59%|█▊ | 20.2M/34.4M [00:01<00:01, 9.97M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  62%|█▊ | 21.4M/34.4M [00:01<00:01, 10.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  69%|██ | 23.6M/34.4M [00:02<00:01, 10.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  72%|██▏| 24.7M/34.4M [00:02<00:00, 10.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  75%|██▎| 26.0M/34.4M [00:02<00:00, 10.8M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  79%|██▎| 27.1M/34.4M [00:02<00:00, 11.0M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  85%|██▌| 29.3M/34.4M [00:02<00:00, 10.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  91%|██▋| 31.4M/34.4M [00:02<00:00, 10.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  96%|██▉| 33.0M/34.4M [00:03<00:00, 11.4M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/34.4M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/13.1M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   9%|▎  | 1.23M/13.1M [00:00<00:00, 12.3M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  20%|▌  | 2.68M/13.1M [00:00<00:00, 13.5M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  33%|▉  | 4.32M/13.1M [00:00<00:00, 14.8M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  49%|█▍ | 6.45M/13.1M [00:00<00:00, 11.7M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  66%|█▉ | 8.66M/13.1M [00:00<00:00, 11.1M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  82%|██▍| 10.8M/13.1M [00:00<00:00, 10.6M Bytes/s]

Get sub-05/s .. _bold.nii.gz: 100%|██▉| 13.1M/13.1M [00:01<00:00, 10.8M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/13.1M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/11.5M [00:00<?, ? Bytes/s]

Get sub-05/s .. _bold.nii.gz:  21%|▌  | 2.38M/11.5M [00:00<00:01, 5.67M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  30%|▉  | 3.45M/11.5M [00:00<00:01, 6.93M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  39%|█▏ | 4.52M/11.5M [00:00<00:00, 7.60M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  59%|█▊ | 6.76M/11.5M [00:00<00:00, 9.04M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  69%|██ | 8.01M/11.5M [00:00<00:00, 9.81M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  79%|██▎| 9.12M/11.5M [00:01<00:00, 9.86M Bytes/s]

Get sub-05/s .. _bold.nii.gz:  97%|██▉| 11.2M/11.5M [00:01<00:00, 9.74M Bytes/s]

Get sub-05/s .. _bold.nii.gz:   0%|            | 0.00/11.5M [00:00<?, ? Bytes/s]
Total:  60%|███████████████▌          | 1.30G/2.17G [02:16<01:31, 9.52M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:   0%|            | 0.00/8.13M [00:00<?, ? Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  18%|▌  | 1.44M/8.13M [00:00<00:00, 14.4M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  48%|█▍ | 3.89M/8.13M [00:00<00:00, 12.4M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  70%|██ | 5.69M/8.13M [00:00<00:00, 10.4M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  89%|██▋| 7.26M/8.13M [00:00<00:00, 9.13M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:   0%|            | 0.00/8.13M [00:00<?, ? Bytes/s]
Total:  60%|███████████████▋          | 1.31G/2.17G [02:17<01:30, 9.49M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   0%|             | 0.00/102M [00:00<?, ? Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   1%|    | 1.45M/102M [00:00<00:06, 14.5M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   4%|▏   | 3.82M/102M [00:00<00:08, 12.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   6%|▏   | 5.83M/102M [00:00<00:08, 10.7M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   8%|▎   | 7.83M/102M [00:00<00:09, 10.3M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  10%|▍   | 10.3M/102M [00:00<00:08, 10.8M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  12%|▍   | 11.9M/102M [00:01<00:09, 9.57M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  13%|▌   | 13.0M/102M [00:01<00:09, 9.71M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  15%|▌   | 14.9M/102M [00:01<00:09, 9.55M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  16%|▋   | 16.7M/102M [00:01<00:07, 11.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  19%|▋   | 18.9M/102M [00:01<00:07, 10.9M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  20%|▊   | 20.5M/102M [00:02<00:08, 9.61M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  22%|▉   | 22.7M/102M [00:02<00:07, 9.93M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  23%|▉   | 23.8M/102M [00:02<00:07, 10.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  25%|▉   | 25.2M/102M [00:02<00:06, 11.0M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  27%|█   | 27.9M/102M [00:02<00:06, 11.5M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  29%|█▏  | 29.9M/102M [00:02<00:06, 10.8M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  31%|█▏  | 31.3M/102M [00:02<00:06, 11.3M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  33%|█▎  | 33.6M/102M [00:03<00:06, 11.0M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  35%|█▍  | 35.2M/102M [00:03<00:05, 12.0M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  37%|█▍  | 37.3M/102M [00:03<00:05, 11.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  39%|█▌  | 40.0M/102M [00:03<00:07, 8.72M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  41%|█▌  | 41.3M/102M [00:04<00:06, 9.09M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  42%|█▋  | 42.4M/102M [00:04<00:06, 9.49M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  44%|█▊  | 44.5M/102M [00:04<00:05, 9.69M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  45%|█▊  | 46.0M/102M [00:04<00:06, 8.18M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  46%|█▊  | 47.1M/102M [00:04<00:07, 7.03M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  48%|█▉  | 48.6M/102M [00:04<00:06, 8.33M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  49%|█▉  | 49.7M/102M [00:05<00:05, 8.86M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  51%|██  | 51.8M/102M [00:05<00:05, 8.72M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  52%|██  | 53.1M/102M [00:05<00:06, 7.94M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  54%|██▏ | 54.6M/102M [00:05<00:06, 7.66M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  55%|██▏ | 56.3M/102M [00:05<00:05, 7.77M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  57%|██▎ | 58.2M/102M [00:06<00:05, 8.19M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  59%|██▎ | 59.9M/102M [00:06<00:05, 8.12M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  60%|██▍ | 61.3M/102M [00:06<00:05, 7.56M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  62%|██▍ | 63.1M/102M [00:06<00:04, 7.93M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  64%|██▌ | 64.8M/102M [00:06<00:04, 7.99M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  65%|██▌ | 66.6M/102M [00:07<00:04, 8.11M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  67%|██▋ | 68.5M/102M [00:07<00:03, 8.41M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  69%|██▊ | 70.3M/102M [00:07<00:03, 8.41M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  71%|██▊ | 72.1M/102M [00:07<00:03, 8.43M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  72%|██▉ | 73.7M/102M [00:08<00:03, 8.19M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  75%|██▉ | 75.9M/102M [00:08<00:02, 8.88M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  76%|███ | 77.0M/102M [00:08<00:03, 7.88M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  78%|███ | 79.2M/102M [00:08<00:02, 8.59M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  80%|███▏| 80.9M/102M [00:08<00:02, 8.42M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  81%|███▎| 82.7M/102M [00:09<00:02, 8.60M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  83%|███▎| 84.7M/102M [00:09<00:02, 6.32M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  85%|███▍| 86.2M/102M [00:09<00:02, 7.41M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  86%|███▍| 87.5M/102M [00:10<00:02, 5.51M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  87%|███▍| 88.9M/102M [00:10<00:02, 5.68M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  89%|███▌| 90.2M/102M [00:10<00:01, 5.87M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  90%|███▌| 91.6M/102M [00:10<00:01, 6.03M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  91%|███▋| 93.0M/102M [00:10<00:01, 6.20M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  93%|███▋| 94.4M/102M [00:11<00:01, 6.71M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  94%|███▋| 95.3M/102M [00:11<00:00, 7.03M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  96%|███▊| 97.1M/102M [00:11<00:00, 7.17M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  97%|███▊| 98.4M/102M [00:11<00:00, 6.82M Bytes/s]

Total:  60%|███████████████▋          | 1.31G/2.17G [02:30<01:38, 8.72M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  98%|███▉| 99.7M/102M [00:11<00:00, 6.67M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz: 100%|████▉| 102M/102M [00:12<00:00, 7.12M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   0%|             | 0.00/102M [00:00<?, ? Bytes/s]

Total:  65%|████████████████▉         | 1.41G/2.17G [02:30<01:21, 9.37M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/22.7M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   6%|▏  | 1.47M/22.7M [00:00<00:02, 10.1M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  13%|▍  | 2.98M/22.7M [00:00<00:02, 6.72M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  19%|▌  | 4.36M/22.7M [00:00<00:02, 8.66M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  26%|▊  | 5.87M/22.7M [00:00<00:02, 7.97M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  32%|▉  | 7.34M/22.7M [00:00<00:02, 7.59M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  39%|█▏ | 8.92M/22.7M [00:01<00:01, 7.55M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  45%|█▎ | 10.3M/22.7M [00:01<00:01, 7.19M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  52%|█▌ | 11.8M/22.7M [00:01<00:01, 7.22M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  59%|█▊ | 13.3M/22.7M [00:01<00:01, 7.21M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  65%|█▉ | 14.7M/22.7M [00:01<00:01, 7.01M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  74%|██▏| 16.7M/22.7M [00:02<00:00, 6.72M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  80%|██▍| 18.2M/22.7M [00:02<00:00, 7.84M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  86%|██▌| 19.5M/22.7M [00:02<00:00, 7.32M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  94%|██▊| 21.3M/22.7M [00:02<00:00, 7.57M Bytes/s]

Get sub-03/s .. _bold.nii.gz: 100%|██▉| 22.6M/22.7M [00:03<00:00, 7.27M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/22.7M [00:00<?, ? Bytes/s]
Total:  66%|█████████████████▏        | 1.43G/2.17G [02:33<01:19, 9.31M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/24.2M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   6%|▏  | 1.55M/24.2M [00:00<00:02, 8.99M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  13%|▍  | 3.12M/24.2M [00:00<00:02, 7.22M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  19%|▌  | 4.68M/24.2M [00:00<00:02, 7.31M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  25%|▊  | 6.14M/24.2M [00:00<00:02, 9.01M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  32%|▉  | 7.83M/24.2M [00:01<00:02, 7.04M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  38%|█▏ | 9.12M/24.2M [00:01<00:01, 8.14M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  45%|█▎ | 10.8M/24.2M [00:01<00:01, 8.04M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  52%|█▌ | 12.5M/24.2M [00:01<00:01, 6.97M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  58%|█▊ | 14.1M/24.2M [00:01<00:01, 7.10M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  65%|█▉ | 15.7M/24.2M [00:02<00:01, 7.14M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  71%|██▏| 17.3M/24.2M [00:02<00:00, 7.23M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  78%|██▎| 18.8M/24.2M [00:02<00:00, 7.30M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  84%|██▌| 20.3M/24.2M [00:02<00:00, 8.56M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  90%|██▋| 21.7M/24.2M [00:02<00:00, 7.90M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  95%|██▊| 23.0M/24.2M [00:03<00:00, 7.37M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/24.2M [00:00<?, ? Bytes/s]
Total:  67%|█████████████████▍        | 1.46G/2.17G [02:37<01:17, 9.25M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/31.2M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   4%|▏  | 1.38M/31.2M [00:00<00:02, 13.7M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   9%|▎  | 2.87M/31.2M [00:00<00:03, 8.73M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  15%|▍  | 4.57M/31.2M [00:00<00:03, 8.39M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  18%|▌  | 5.76M/31.2M [00:00<00:03, 7.24M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  25%|▋  | 7.69M/31.2M [00:00<00:02, 7.96M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  30%|▉  | 9.28M/31.2M [00:01<00:02, 7.83M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  35%|█  | 11.0M/31.2M [00:01<00:02, 6.75M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  40%|█▏ | 12.5M/31.2M [00:01<00:02, 8.11M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  44%|█▎ | 13.8M/31.2M [00:01<00:02, 7.41M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  49%|█▍ | 15.4M/31.2M [00:01<00:02, 7.47M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  54%|█▌ | 16.9M/31.2M [00:02<00:01, 7.39M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  60%|█▊ | 18.6M/31.2M [00:02<00:01, 7.61M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  64%|█▉ | 20.1M/31.2M [00:02<00:01, 7.47M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  69%|██ | 21.5M/31.2M [00:02<00:01, 7.19M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  76%|██▎| 23.7M/31.2M [00:03<00:01, 7.26M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  79%|██▎| 24.6M/31.2M [00:03<00:00, 7.60M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  84%|██▌| 26.2M/31.2M [00:03<00:00, 7.48M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  89%|██▋| 27.9M/31.2M [00:03<00:00, 7.47M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  95%|██▊| 29.7M/31.2M [00:03<00:00, 7.79M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/31.2M [00:00<?, ? Bytes/s]
Total:  69%|█████████████████▊        | 1.49G/2.17G [02:41<01:14, 9.19M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/12.0M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:  14%|▍  | 1.63M/12.0M [00:00<00:01, 7.79M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  24%|▋  | 2.90M/12.0M [00:00<00:00, 9.74M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  38%|█▏ | 4.57M/12.0M [00:00<00:00, 8.73M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  51%|█▌ | 6.09M/12.0M [00:00<00:00, 8.04M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  68%|██ | 8.17M/12.0M [00:00<00:00, 8.73M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  80%|██▍| 9.55M/12.0M [00:01<00:00, 7.93M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  95%|██▊| 11.3M/12.0M [00:01<00:00, 8.12M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/12.0M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/10.4M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:  16%|▍  | 1.70M/10.4M [00:00<00:01, 8.07M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  30%|▉  | 3.10M/10.4M [00:00<00:00, 10.5M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  47%|█▍ | 4.86M/10.4M [00:00<00:00, 9.28M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  65%|█▉ | 6.76M/10.4M [00:00<00:00, 9.14M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  81%|██▍| 8.41M/10.4M [00:00<00:00, 8.66M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  98%|██▉| 10.1M/10.4M [00:01<00:00, 8.50M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/10.4M [00:00<?, ? Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:   0%|            | 0.00/7.97M [00:00<?, ? Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  23%|▋  | 1.82M/7.97M [00:00<00:00, 8.66M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  39%|█▏ | 3.09M/7.97M [00:00<00:00, 10.3M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  62%|█▊ | 4.94M/7.97M [00:00<00:00, 9.38M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:  88%|██▋| 7.03M/7.97M [00:00<00:00, 9.71M Bytes/s]

Get sub-03/s .. t_T1w.nii.gz:   0%|            | 0.00/7.97M [00:00<?, ? Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   0%|             | 0.00/107M [00:00<?, ? Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   2%|    | 1.91M/107M [00:00<00:11, 8.94M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   4%|▏   | 3.85M/107M [00:00<00:11, 9.19M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   5%|▏   | 5.02M/107M [00:00<00:10, 9.87M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   7%|▎   | 7.34M/107M [00:00<00:09, 10.4M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   9%|▎   | 9.26M/107M [00:00<00:09, 9.90M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  11%|▍   | 11.3M/107M [00:01<00:09, 9.80M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  13%|▌   | 13.4M/107M [00:01<00:09, 9.93M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  14%|▌   | 15.2M/107M [00:01<00:09, 9.36M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  16%|▋   | 17.4M/107M [00:01<00:09, 9.82M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  18%|▋   | 19.6M/107M [00:01<00:08, 10.0M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  20%|▊   | 21.3M/107M [00:02<00:09, 9.31M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  22%|▉   | 23.5M/107M [00:02<00:08, 9.76M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  24%|▉   | 25.7M/107M [00:02<00:08, 9.95M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  26%|█   | 27.7M/107M [00:02<00:08, 9.80M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  27%|█   | 28.7M/107M [00:02<00:08, 9.67M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  28%|█▏  | 30.1M/107M [00:03<00:07, 10.6M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  30%|█▏  | 31.9M/107M [00:03<00:07, 9.84M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  31%|█▏  | 33.2M/107M [00:03<00:07, 10.2M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  33%|█▎  | 34.9M/107M [00:03<00:06, 11.6M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  35%|█▍  | 36.9M/107M [00:03<00:06, 10.8M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  37%|█▍  | 39.1M/107M [00:03<00:06, 10.6M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  38%|█▌  | 40.3M/107M [00:03<00:06, 11.0M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  39%|█▌  | 41.7M/107M [00:04<00:05, 11.5M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  40%|█▌  | 42.9M/107M [00:04<00:05, 11.2M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  42%|█▋  | 44.5M/107M [00:04<00:05, 12.2M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  44%|█▊  | 47.4M/107M [00:04<00:04, 12.9M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  46%|█▊  | 49.5M/107M [00:04<00:06, 8.83M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  48%|█▉  | 51.0M/107M [00:05<00:05, 9.77M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  49%|█▉  | 52.4M/107M [00:05<00:05, 10.4M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  51%|██  | 53.9M/107M [00:05<00:05, 9.70M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  52%|██  | 55.4M/107M [00:05<00:04, 10.9M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  54%|██▏ | 57.5M/107M [00:05<00:04, 10.5M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  56%|██▏ | 59.6M/107M [00:05<00:04, 10.3M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  58%|██▎ | 61.7M/107M [00:06<00:04, 10.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  60%|██▍ | 63.7M/107M [00:06<00:04, 10.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  62%|██▍ | 66.1M/107M [00:06<00:03, 10.4M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  64%|██▌ | 68.3M/107M [00:06<00:03, 10.4M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  66%|██▋ | 70.5M/107M [00:06<00:03, 10.4M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  68%|██▋ | 72.8M/107M [00:07<00:03, 10.5M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  70%|██▊ | 75.1M/107M [00:07<00:02, 10.7M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  72%|██▉ | 77.2M/107M [00:07<00:02, 10.5M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  74%|██▉ | 79.3M/107M [00:07<00:02, 10.4M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  76%|███ | 81.3M/107M [00:07<00:02, 9.99M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  78%|███▏| 83.4M/107M [00:08<00:02, 10.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  80%|███▏| 85.6M/107M [00:08<00:02, 10.1M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  82%|███▎| 87.1M/107M [00:08<00:02, 8.32M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  83%|███▎| 88.5M/107M [00:08<00:02, 6.75M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  84%|███▎| 89.6M/107M [00:09<00:02, 7.17M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  85%|███▍| 90.9M/107M [00:09<00:01, 7.91M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  87%|███▍| 92.8M/107M [00:09<00:01, 8.17M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  89%|███▌| 94.6M/107M [00:09<00:01, 8.40M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  91%|███▌| 96.5M/107M [00:09<00:01, 8.59M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  92%|███▋| 98.4M/107M [00:10<00:00, 8.76M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  94%|████▋| 100M/107M [00:10<00:00, 8.88M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  96%|████▊| 102M/107M [00:10<00:00, 9.00M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:  98%|████▉| 104M/107M [00:10<00:00, 9.20M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz: 100%|████▉| 106M/107M [00:10<00:00, 9.22M Bytes/s]

Get sub-03/s .. t_dwi.nii.gz:   0%|             | 0.00/107M [00:00<?, ? Bytes/s]

Total:  75%|███████████████████▍      | 1.62G/2.17G [02:58<00:59, 9.13M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/23.1M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   9%|▎  | 2.01M/23.1M [00:00<00:02, 9.61M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  17%|▌  | 3.89M/23.1M [00:00<00:01, 13.3M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  28%|▊  | 6.60M/23.1M [00:00<00:02, 6.19M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  34%|█  | 7.79M/23.1M [00:01<00:02, 6.87M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  40%|█▏ | 9.22M/23.1M [00:01<00:01, 7.46M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  46%|█▍ | 10.7M/23.1M [00:01<00:01, 6.69M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  53%|█▌ | 12.2M/23.1M [00:01<00:01, 8.02M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  58%|█▊ | 13.5M/23.1M [00:01<00:01, 7.57M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  65%|█▉ | 15.1M/23.1M [00:02<00:01, 7.45M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  71%|██▏| 16.5M/23.1M [00:02<00:00, 7.19M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  79%|██▎| 18.3M/23.1M [00:02<00:00, 7.55M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  86%|██▌| 19.9M/23.1M [00:02<00:00, 7.56M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  91%|██▋| 21.1M/23.1M [00:02<00:00, 7.13M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  99%|██▉| 22.9M/23.1M [00:03<00:00, 7.49M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/23.1M [00:00<?, ? Bytes/s]
Total:  76%|███████████████████▋      | 1.65G/2.17G [03:01<00:57, 9.08M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/24.5M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   7%|▏  | 1.62M/24.5M [00:00<00:02, 7.73M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  12%|▎  | 2.97M/24.5M [00:00<00:02, 10.1M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  19%|▌  | 4.69M/24.5M [00:00<00:02, 9.01M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  25%|▊  | 6.24M/24.5M [00:00<00:02, 8.30M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  32%|▉  | 7.96M/24.5M [00:00<00:02, 8.27M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  40%|█▏ | 9.70M/24.5M [00:01<00:01, 8.28M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  46%|█▎ | 11.2M/24.5M [00:01<00:01, 7.87M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  53%|█▌ | 12.9M/24.5M [00:01<00:01, 7.94M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  61%|█▊ | 14.9M/24.5M [00:02<00:01, 5.15M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  66%|█▉ | 16.2M/24.5M [00:02<00:01, 6.07M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  71%|██▏| 17.5M/24.5M [00:02<00:01, 6.83M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  76%|██▎| 18.7M/24.5M [00:02<00:00, 6.52M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  82%|██▍| 20.0M/24.5M [00:02<00:00, 6.32M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  87%|██▌| 21.2M/24.5M [00:03<00:00, 6.21M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  92%|██▊| 22.5M/24.5M [00:03<00:00, 6.12M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  97%|██▉| 23.8M/24.5M [00:03<00:00, 6.10M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/24.5M [00:00<?, ? Bytes/s]
Total:  77%|████████████████████      | 1.67G/2.17G [03:05<00:55, 9.02M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/31.8M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   4%|   | 1.32M/31.8M [00:00<00:04, 6.34M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   8%|▏  | 2.41M/31.8M [00:00<00:03, 8.19M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  12%|▎  | 3.76M/31.8M [00:00<00:03, 7.21M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  17%|▍  | 5.27M/31.8M [00:00<00:03, 7.19M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  21%|▋  | 6.67M/31.8M [00:01<00:04, 5.80M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  25%|▋  | 7.86M/31.8M [00:01<00:03, 6.90M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  29%|▉  | 9.35M/31.8M [00:01<00:03, 6.94M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  34%|█  | 10.8M/31.8M [00:01<00:03, 5.91M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  38%|█▏ | 12.0M/31.8M [00:01<00:02, 6.91M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  42%|█▎ | 13.4M/31.8M [00:01<00:02, 6.81M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  46%|█▍ | 14.8M/31.8M [00:02<00:02, 6.71M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  51%|█▌ | 16.2M/31.8M [00:02<00:02, 6.76M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  55%|█▋ | 17.5M/31.8M [00:02<00:02, 6.59M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  60%|█▊ | 18.9M/31.8M [00:02<00:01, 6.65M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  64%|█▉ | 20.2M/31.8M [00:03<00:01, 6.47M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  69%|██ | 21.9M/31.8M [00:03<00:01, 6.94M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  73%|██▏| 23.3M/31.8M [00:03<00:01, 6.78M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  77%|██▎| 24.6M/31.8M [00:03<00:01, 6.60M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  82%|██▍| 26.1M/31.8M [00:03<00:00, 6.87M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  87%|██▌| 27.5M/31.8M [00:04<00:00, 6.75M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  91%|██▋| 28.8M/31.8M [00:04<00:00, 6.68M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  96%|██▊| 30.4M/31.8M [00:04<00:00, 6.89M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/31.8M [00:00<?, ? Bytes/s]
Total:  78%|████████████████████▍     | 1.70G/2.17G [03:10<00:52, 8.95M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/12.2M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:  12%|▎  | 1.44M/12.2M [00:00<00:01, 6.79M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  22%|▋  | 2.67M/12.2M [00:00<00:01, 9.03M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  35%|█  | 4.29M/12.2M [00:00<00:01, 3.96M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  47%|█▍ | 5.73M/12.2M [00:01<00:01, 5.52M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  58%|█▋ | 7.02M/12.2M [00:01<00:00, 6.58M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  67%|█▉ | 8.10M/12.2M [00:01<00:00, 5.20M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  75%|██▎| 9.17M/12.2M [00:01<00:00, 5.36M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  83%|██▍| 10.1M/12.2M [00:01<00:00, 6.06M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  94%|██▊| 11.4M/12.2M [00:02<00:00, 5.04M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/12.2M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/10.6M [00:00<?, ? Bytes/s]

Get sub-03/s .. _bold.nii.gz:  11%|▎  | 1.18M/10.6M [00:00<00:01, 5.68M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  22%|▋  | 2.37M/10.6M [00:00<00:01, 5.60M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  34%|█  | 3.57M/10.6M [00:00<00:01, 5.70M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  45%|█▎ | 4.73M/10.6M [00:00<00:00, 7.09M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  57%|█▋ | 5.97M/10.6M [00:00<00:00, 6.60M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  69%|██ | 7.30M/10.6M [00:01<00:00, 5.43M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  80%|██▍| 8.48M/10.6M [00:01<00:00, 6.53M Bytes/s]

Get sub-03/s .. _bold.nii.gz:  93%|██▊| 9.82M/10.6M [00:01<00:00, 6.48M Bytes/s]

Get sub-03/s .. _bold.nii.gz:   0%|            | 0.00/10.6M [00:00<?, ? Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:   0%|            | 0.00/10.1M [00:00<?, ? Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  13%|▍  | 1.30M/10.1M [00:00<00:01, 6.16M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  26%|▊  | 2.62M/10.1M [00:00<00:01, 6.22M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  39%|█▏ | 3.95M/10.1M [00:00<00:00, 6.24M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  52%|█▌ | 5.29M/10.1M [00:00<00:00, 6.33M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  66%|█▉ | 6.65M/10.1M [00:01<00:00, 6.38M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  79%|██▎| 8.01M/10.1M [00:01<00:00, 7.56M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  93%|██▊| 9.41M/10.1M [00:01<00:00, 6.16M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:   0%|            | 0.00/10.1M [00:00<?, ? Bytes/s]
Total:  80%|████████████████████▊     | 1.74G/2.17G [03:17<00:49, 8.82M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   0%|             | 0.00/102M [00:00<?, ? Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   1%|    | 1.03M/102M [00:00<00:09, 10.3M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   3%|    | 2.78M/102M [00:00<00:15, 6.35M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   4%|▏   | 4.09M/102M [00:00<00:12, 8.14M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   5%|▏   | 5.54M/102M [00:00<00:12, 7.52M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   7%|▎   | 6.83M/102M [00:00<00:13, 7.04M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   8%|▎   | 8.31M/102M [00:01<00:13, 7.03M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  10%|▍   | 9.85M/102M [00:01<00:15, 6.02M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  11%|▍   | 11.2M/102M [00:01<00:12, 7.23M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  12%|▍   | 12.3M/102M [00:01<00:13, 6.64M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  13%|▌   | 13.7M/102M [00:01<00:13, 6.68M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  15%|▌   | 15.3M/102M [00:02<00:12, 6.96M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  16%|▋   | 16.7M/102M [00:02<00:12, 6.82M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  18%|▋   | 18.2M/102M [00:02<00:12, 6.85M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  19%|▊   | 19.6M/102M [00:02<00:12, 6.84M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  21%|▊   | 21.3M/102M [00:03<00:12, 6.64M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  22%|▉   | 22.8M/102M [00:03<00:12, 6.31M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  23%|▉   | 23.9M/102M [00:03<00:11, 7.10M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  25%|▉   | 25.4M/102M [00:03<00:10, 7.11M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  26%|█   | 26.8M/102M [00:03<00:11, 6.78M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  28%|█   | 28.2M/102M [00:04<00:10, 6.86M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  29%|█▏  | 29.7M/102M [00:04<00:10, 7.05M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  31%|█▏  | 31.2M/102M [00:04<00:10, 7.02M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  32%|█▎  | 32.7M/102M [00:04<00:09, 7.07M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  33%|█▎  | 34.1M/102M [00:04<00:09, 6.85M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  35%|█▍  | 35.6M/102M [00:05<00:09, 7.02M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  36%|█▍  | 37.1M/102M [00:05<00:09, 6.94M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  38%|█▌  | 38.4M/102M [00:05<00:09, 6.82M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  39%|█▌  | 39.8M/102M [00:05<00:09, 6.77M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  40%|█▌  | 41.3M/102M [00:05<00:08, 6.83M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  42%|█▋  | 42.8M/102M [00:06<00:08, 6.91M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  43%|█▋  | 44.2M/102M [00:06<00:08, 6.77M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  44%|█▊  | 45.5M/102M [00:06<00:08, 6.63M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  46%|█▊  | 47.3M/102M [00:06<00:08, 6.29M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  47%|█▉  | 48.3M/102M [00:07<00:08, 6.74M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  49%|█▉  | 49.9M/102M [00:07<00:07, 6.95M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  50%|██  | 51.2M/102M [00:07<00:07, 6.86M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  51%|██  | 52.6M/102M [00:07<00:07, 6.78M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  53%|██  | 54.2M/102M [00:07<00:06, 6.97M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  55%|██▏ | 55.8M/102M [00:08<00:06, 7.25M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  56%|██▏ | 57.1M/102M [00:08<00:06, 6.89M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  57%|██▎ | 58.5M/102M [00:08<00:06, 6.80M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  59%|██▎ | 60.1M/102M [00:08<00:06, 6.80M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  60%|██▍ | 61.5M/102M [00:08<00:05, 6.94M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  62%|██▍ | 63.4M/102M [00:09<00:05, 7.51M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  63%|██▌ | 64.5M/102M [00:09<00:05, 6.93M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  64%|██▌ | 65.9M/102M [00:09<00:05, 6.89M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  66%|██▋ | 67.4M/102M [00:09<00:04, 6.99M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  67%|██▋ | 69.0M/102M [00:09<00:04, 7.17M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  69%|██▊ | 70.5M/102M [00:10<00:04, 7.15M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  70%|██▊ | 72.0M/102M [00:10<00:04, 7.05M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  72%|██▊ | 73.5M/102M [00:10<00:04, 7.19M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  73%|██▉ | 75.2M/102M [00:10<00:03, 7.36M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  75%|██▉ | 76.6M/102M [00:11<00:03, 7.26M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  76%|███ | 78.2M/102M [00:11<00:03, 7.35M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  78%|███ | 79.9M/102M [00:11<00:03, 7.48M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  80%|███▏| 81.5M/102M [00:11<00:02, 7.59M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  81%|███▏| 83.1M/102M [00:11<00:02, 7.59M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  83%|███▎| 85.0M/102M [00:12<00:02, 7.96M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  84%|███▍| 86.3M/102M [00:12<00:02, 7.48M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  85%|███▍| 87.2M/102M [00:12<00:01, 7.59M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  86%|███▍| 88.4M/102M [00:12<00:01, 8.45M Bytes/s]

Total:  80%|████████████████████▊     | 1.74G/2.17G [03:30<00:52, 8.27M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  88%|███▌| 89.8M/102M [00:12<00:01, 7.71M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  89%|███▌| 90.7M/102M [00:12<00:01, 7.73M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  90%|███▌| 91.7M/102M [00:12<00:01, 8.28M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  91%|███▋| 93.4M/102M [00:13<00:01, 8.34M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  93%|███▋| 95.2M/102M [00:13<00:00, 8.29M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  95%|███▊| 96.9M/102M [00:13<00:00, 8.32M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  96%|███▊| 97.8M/102M [00:13<00:00, 8.29M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  97%|███▊| 98.8M/102M [00:13<00:00, 8.53M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  97%|███▉| 99.7M/102M [00:13<00:00, 8.48M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  99%|████▉| 102M/102M [00:14<00:00, 8.76M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   0%|             | 0.00/102M [00:00<?, ? Bytes/s]

Total:  85%|██████████████████████    | 1.84G/2.17G [03:31<00:38, 8.69M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/24.6M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   8%|▏  | 1.93M/24.6M [00:00<00:02, 9.21M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  14%|▍  | 3.45M/24.6M [00:00<00:01, 11.6M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  23%|▋  | 5.56M/24.6M [00:00<00:01, 10.8M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  30%|▉  | 7.48M/24.6M [00:00<00:01, 10.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  37%|█  | 9.13M/24.6M [00:00<00:01, 9.17M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  48%|█▍ | 11.7M/24.6M [00:01<00:01, 10.3M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  56%|█▋ | 13.8M/24.6M [00:01<00:01, 10.2M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  63%|█▉ | 15.4M/24.6M [00:01<00:00, 9.33M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  67%|██ | 16.5M/24.6M [00:01<00:00, 9.44M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  73%|██▏| 18.0M/24.6M [00:01<00:00, 10.5M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  82%|██▍| 20.3M/24.6M [00:01<00:00, 10.7M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  92%|██▋| 22.6M/24.6M [00:02<00:00, 10.7M Bytes/s]

Get sub-04/s .. _bold.nii.gz: 100%|██▉| 24.5M/24.6M [00:02<00:00, 10.3M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/24.6M [00:00<?, ? Bytes/s]
Total:  86%|██████████████████████▎   | 1.86G/2.17G [03:34<00:35, 8.69M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/26.2M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   5%|▏  | 1.31M/26.2M [00:00<00:01, 13.0M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  15%|▍  | 3.89M/26.2M [00:00<00:01, 12.5M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  24%|▋  | 6.31M/26.2M [00:00<00:02, 9.45M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  31%|▉  | 8.15M/26.2M [00:00<00:01, 11.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  38%|█▏ | 10.0M/26.2M [00:00<00:01, 10.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  45%|█▎ | 11.8M/26.2M [00:01<00:01, 9.73M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  53%|█▌ | 13.8M/26.2M [00:01<00:01, 9.60M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  60%|█▊ | 15.8M/26.2M [00:01<00:01, 9.55M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  64%|█▉ | 16.9M/26.2M [00:01<00:00, 9.57M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  70%|██ | 18.4M/26.2M [00:01<00:00, 10.7M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  81%|██▍| 21.2M/26.2M [00:01<00:00, 11.7M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  89%|██▋| 23.4M/26.2M [00:02<00:00, 11.2M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  99%|██▉| 25.8M/26.2M [00:02<00:00, 11.3M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/26.2M [00:00<?, ? Bytes/s]
Total:  87%|██████████████████████▋   | 1.89G/2.17G [03:37<00:32, 8.70M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/33.7M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   6%|▏  | 2.02M/33.7M [00:00<00:01, 20.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  14%|▍  | 4.64M/33.7M [00:00<00:02, 10.3M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  21%|▋  | 7.15M/33.7M [00:00<00:02, 11.0M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  27%|▊  | 9.00M/33.7M [00:00<00:02, 10.2M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  31%|▉  | 10.5M/33.7M [00:00<00:02, 11.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  38%|█▏ | 13.0M/33.7M [00:01<00:01, 11.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  44%|█▎ | 14.9M/33.7M [00:01<00:01, 10.6M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  50%|█▌ | 17.0M/33.7M [00:01<00:01, 10.3M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  56%|█▋ | 19.0M/33.7M [00:01<00:01, 10.0M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  63%|█▉ | 21.4M/33.7M [00:01<00:01, 10.6M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  69%|██ | 23.3M/33.7M [00:02<00:01, 9.99M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  76%|██▎| 25.5M/33.7M [00:02<00:00, 10.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  82%|██▍| 27.8M/33.7M [00:02<00:00, 10.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  88%|██▋| 29.9M/33.7M [00:02<00:00, 10.2M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  92%|██▊| 31.1M/33.7M [00:02<00:00, 10.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  97%|██▉| 32.7M/33.7M [00:03<00:00, 11.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/33.7M [00:00<?, ? Bytes/s]

Total:  89%|███████████████████████   | 1.92G/2.17G [03:40<00:28, 8.71M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/12.9M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:  23%|▋  | 2.97M/12.9M [00:00<00:00, 14.9M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  45%|█▎ | 5.76M/12.9M [00:00<00:00, 12.7M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  61%|█▊ | 7.84M/12.9M [00:00<00:00, 11.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  79%|██▎| 10.1M/12.9M [00:00<00:00, 11.2M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  95%|██▊| 12.3M/12.9M [00:01<00:00, 10.8M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/12.9M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/11.2M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:  11%|▎  | 1.24M/11.2M [00:00<00:00, 12.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  23%|▋  | 2.61M/11.2M [00:00<00:00, 13.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  44%|█▎ | 4.89M/11.2M [00:00<00:00, 12.0M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  67%|██ | 7.46M/11.2M [00:00<00:00, 11.2M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  79%|██▎| 8.82M/11.2M [00:00<00:00, 11.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  97%|██▉| 10.9M/11.2M [00:00<00:00, 10.8M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/11.2M [00:00<?, ? Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:   0%|            | 0.00/9.72M [00:00<?, ? Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  29%|▊  | 2.80M/9.72M [00:00<00:00, 14.0M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  53%|█▌ | 5.17M/9.72M [00:00<00:00, 12.7M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  67%|██ | 6.48M/9.72M [00:00<00:00, 11.2M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:  81%|██▍| 7.86M/9.72M [00:00<00:00, 11.9M Bytes/s]

Get sub-04/s .. t_T1w.nii.gz:   0%|            | 0.00/9.72M [00:00<?, ? Bytes/s]
Total:  90%|███████████████████████▍  | 1.96G/2.17G [03:44<00:24, 8.71M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   0%|             | 0.00/105M [00:00<?, ? Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   1%|    | 1.02M/105M [00:00<00:10, 10.1M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   2%|    | 2.13M/105M [00:00<00:09, 10.7M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   3%|▏   | 3.57M/105M [00:00<00:08, 12.4M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   5%|▏   | 4.95M/105M [00:00<00:07, 12.9M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   7%|▎   | 7.41M/105M [00:00<00:08, 11.2M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   9%|▎   | 9.80M/105M [00:00<00:08, 11.3M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  11%|▍   | 12.0M/105M [00:01<00:08, 10.9M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  14%|▌   | 14.2M/105M [00:01<00:08, 10.8M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  16%|▋   | 16.6M/105M [00:01<00:08, 10.9M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  18%|▋   | 18.5M/105M [00:01<00:08, 10.3M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  19%|▊   | 19.7M/105M [00:01<00:08, 10.5M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  20%|▊   | 21.2M/105M [00:01<00:07, 11.3M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  23%|▉   | 23.9M/105M [00:02<00:06, 11.8M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  25%|▉   | 26.0M/105M [00:02<00:07, 11.1M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  26%|█   | 27.5M/105M [00:02<00:06, 11.6M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  28%|█▏  | 29.6M/105M [00:02<00:06, 11.2M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  30%|█▏  | 31.1M/105M [00:02<00:06, 11.8M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  32%|█▎  | 33.4M/105M [00:02<00:06, 11.5M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  33%|█▎  | 34.7M/105M [00:03<00:06, 11.4M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  34%|█▍  | 36.1M/105M [00:03<00:05, 12.0M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  37%|█▍  | 38.7M/105M [00:03<00:05, 12.0M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  39%|█▌  | 40.6M/105M [00:03<00:07, 8.09M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  40%|█▌  | 42.0M/105M [00:03<00:07, 8.83M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  41%|█▋  | 43.2M/105M [00:04<00:09, 6.54M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  42%|█▋  | 44.4M/105M [00:04<00:09, 6.45M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  43%|█▋  | 45.6M/105M [00:04<00:08, 7.27M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  45%|█▊  | 46.8M/105M [00:04<00:07, 8.06M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  46%|█▊  | 48.4M/105M [00:04<00:06, 8.13M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  48%|█▉  | 50.3M/105M [00:05<00:06, 8.38M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  50%|█▉  | 52.2M/105M [00:05<00:06, 8.62M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  51%|██  | 53.6M/105M [00:05<00:08, 5.71M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  53%|██  | 55.1M/105M [00:05<00:08, 6.11M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  54%|██▏ | 56.2M/105M [00:06<00:07, 6.86M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  55%|██▏ | 57.6M/105M [00:06<00:05, 7.95M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  57%|██▎ | 59.4M/105M [00:06<00:05, 8.30M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  58%|██▎ | 61.2M/105M [00:06<00:05, 8.60M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  59%|██▎ | 62.2M/105M [00:06<00:04, 8.78M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  61%|██▍ | 63.8M/105M [00:06<00:04, 8.69M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  62%|██▍ | 65.0M/105M [00:06<00:04, 9.52M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  65%|██▌ | 67.8M/105M [00:07<00:03, 10.8M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  66%|██▋ | 69.3M/105M [00:07<00:03, 9.69M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  67%|██▋ | 70.5M/105M [00:07<00:03, 9.72M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  69%|██▋ | 71.9M/105M [00:07<00:03, 10.8M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  71%|██▊ | 74.3M/105M [00:07<00:02, 11.0M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  73%|██▉ | 76.5M/105M [00:08<00:02, 10.8M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  75%|███ | 79.1M/105M [00:08<00:02, 11.3M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  77%|███ | 81.1M/105M [00:08<00:02, 10.7M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  80%|███▏| 83.6M/105M [00:08<00:01, 11.1M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  82%|███▎| 85.6M/105M [00:08<00:01, 10.5M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  83%|███▎| 86.8M/105M [00:08<00:01, 10.6M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  84%|███▎| 88.4M/105M [00:09<00:01, 11.6M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  86%|███▍| 90.2M/105M [00:09<00:01, 10.6M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  88%|███▌| 92.8M/105M [00:09<00:01, 11.1M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  91%|███▌| 94.9M/105M [00:09<00:00, 10.8M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  93%|███▋| 97.3M/105M [00:09<00:00, 11.0M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  95%|███▊| 99.7M/105M [00:10<00:00, 11.1M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  96%|████▊| 101M/105M [00:10<00:00, 7.62M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  98%|████▉| 103M/105M [00:10<00:00, 8.80M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:  99%|████▉| 104M/105M [00:10<00:00, 9.32M Bytes/s]

Get sub-04/s .. t_dwi.nii.gz:   0%|             | 0.00/105M [00:00<?, ? Bytes/s]

Total:  95%|████████████████████████▋ | 2.06G/2.17G [03:55<00:12, 8.74M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/24.7M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   7%|▏  | 1.84M/24.7M [00:00<00:02, 8.79M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  13%|▍  | 3.28M/24.7M [00:00<00:01, 11.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  21%|▌  | 5.07M/24.7M [00:00<00:02, 9.63M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  28%|▊  | 6.89M/24.7M [00:00<00:01, 9.19M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  35%|█  | 8.70M/24.7M [00:00<00:01, 8.98M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  45%|█▎ | 11.2M/24.7M [00:01<00:01, 9.75M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  51%|█▌ | 12.6M/24.7M [00:01<00:01, 8.87M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  61%|█▊ | 15.1M/24.7M [00:01<00:01, 8.66M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  66%|█▉ | 16.3M/24.7M [00:01<00:00, 9.22M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  76%|██▎| 18.6M/24.7M [00:01<00:00, 9.57M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  84%|██▌| 20.7M/24.7M [00:02<00:00, 9.72M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  95%|██▊| 23.4M/24.7M [00:02<00:00, 9.10M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/24.7M [00:00<?, ? Bytes/s]
Total:  96%|████████████████████████▉ | 2.09G/2.17G [03:58<00:09, 8.74M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/26.3M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|    | 33.4k/26.3M [00:00<03:08, 139k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|    | 68.2k/26.3M [00:00<02:57, 147k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   1%|     | 138k/26.3M [00:00<01:55, 227k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   1%|     | 207k/26.3M [00:00<01:37, 266k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   1%|     | 277k/26.3M [00:01<01:29, 289k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   1%|     | 347k/26.3M [00:01<01:25, 303k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   2%|     | 416k/26.3M [00:01<01:22, 312k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   2%|     | 503k/26.3M [00:01<01:14, 344k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   2%|     | 590k/26.3M [00:01<01:10, 366k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   3%|▏    | 677k/26.3M [00:02<01:07, 381k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   3%|▏    | 764k/26.3M [00:02<01:05, 391k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   3%|▏    | 869k/26.3M [00:02<01:00, 423k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   4%|▏    | 973k/26.3M [00:02<00:56, 446k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   4%|▏   | 1.08M/26.3M [00:02<00:54, 460k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   5%|▏   | 1.18M/26.3M [00:03<00:53, 471k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   5%|▏   | 1.30M/26.3M [00:03<00:49, 501k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   5%|▏   | 1.43M/26.3M [00:03<00:47, 527k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   6%|▏   | 1.57M/26.3M [00:03<00:43, 565k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   6%|▎   | 1.69M/26.3M [00:04<00:42, 572k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   7%|▎   | 1.84M/26.3M [00:04<00:39, 621k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   8%|▎   | 1.98M/26.3M [00:04<00:38, 636k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   8%|▎   | 2.14M/26.3M [00:04<00:36, 668k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   9%|▎   | 2.31M/26.3M [00:04<00:33, 712k Bytes/s]

Get sub-04/s .. _bold.nii.gz:   9%|▍   | 2.49M/26.3M [00:05<00:31, 747k Bytes/s]

Get sub-04/s .. _bold.nii.gz:  10%|▍   | 2.66M/26.3M [00:05<00:30, 777k Bytes/s]

Get sub-04/s .. _bold.nii.gz:  11%|▍   | 2.85M/26.3M [00:05<00:28, 817k Bytes/s]

Get sub-04/s .. _bold.nii.gz:  12%|▍   | 3.06M/26.3M [00:05<00:26, 864k Bytes/s]

Get sub-04/s .. _bold.nii.gz:  12%|▍   | 3.27M/26.3M [00:05<00:25, 905k Bytes/s]

Get sub-04/s .. _bold.nii.gz:  13%|▌   | 3.50M/26.3M [00:06<00:23, 953k Bytes/s]

Get sub-04/s .. _bold.nii.gz:  14%|▌   | 3.72M/26.3M [00:06<00:22, 995k Bytes/s]

Get sub-04/s .. _bold.nii.gz:  15%|▍  | 3.97M/26.3M [00:06<00:21, 1.04M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  16%|▍  | 4.23M/26.3M [00:06<00:19, 1.10M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  17%|▌  | 4.49M/26.3M [00:06<00:16, 1.30M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  18%|▌  | 4.68M/26.3M [00:07<00:15, 1.42M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  19%|▌  | 5.08M/26.3M [00:07<00:17, 1.19M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  21%|▌  | 5.40M/26.3M [00:07<00:16, 1.27M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  22%|▋  | 5.73M/26.3M [00:07<00:15, 1.36M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  23%|▋  | 6.06M/26.3M [00:07<00:12, 1.61M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  24%|▋  | 6.42M/26.3M [00:08<00:13, 1.46M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  26%|▊  | 6.81M/26.3M [00:08<00:12, 1.57M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  27%|▊  | 7.21M/26.3M [00:08<00:11, 1.66M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  29%|▊  | 7.62M/26.3M [00:08<00:10, 1.76M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  31%|▉  | 8.06M/26.3M [00:09<00:08, 2.10M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  32%|▉  | 8.53M/26.3M [00:09<00:09, 1.90M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  34%|█  | 9.02M/26.3M [00:09<00:08, 2.02M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  36%|█  | 9.52M/26.3M [00:09<00:07, 2.13M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  38%|█▏ | 10.1M/26.3M [00:09<00:06, 2.57M Bytes/s]

Total:  96%|████████████████████████▉ | 2.09G/2.17G [04:10<00:10, 8.35M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  41%|█▏ | 10.7M/26.3M [00:10<00:06, 2.34M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  43%|█▎ | 11.3M/26.3M [00:10<00:06, 2.50M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  45%|█▎ | 11.9M/26.3M [00:10<00:04, 3.01M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  48%|█▍ | 12.6M/26.3M [00:10<00:05, 2.74M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  51%|█▌ | 13.3M/26.3M [00:10<00:03, 3.33M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  54%|█▌ | 14.1M/26.3M [00:11<00:04, 3.04M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  57%|█▋ | 14.9M/26.3M [00:11<00:03, 3.69M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  60%|█▊ | 15.7M/26.3M [00:11<00:02, 3.81M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  63%|█▉ | 16.6M/26.3M [00:11<00:02, 3.51M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  67%|██ | 17.6M/26.3M [00:11<00:02, 4.27M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  71%|██ | 18.6M/26.3M [00:12<00:01, 3.94M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  75%|██▏| 19.6M/26.3M [00:12<00:01, 4.77M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  79%|██▎| 20.7M/26.3M [00:12<00:01, 4.37M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  83%|██▍| 21.9M/26.3M [00:12<00:00, 4.70M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  88%|██▋| 23.1M/26.3M [00:13<00:00, 5.01M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  93%|██▊| 24.4M/26.3M [00:13<00:00, 6.05M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  98%|██▉| 25.7M/26.3M [00:13<00:00, 6.15M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/26.3M [00:00<?, ? Bytes/s]
Total:  97%|█████████████████████████▎| 2.11G/2.17G [04:13<00:06, 8.34M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/33.8M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   4%|   | 1.34M/33.8M [00:00<00:02, 13.3M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   9%|▎  | 2.88M/33.8M [00:00<00:03, 8.84M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  13%|▍  | 4.47M/33.8M [00:00<00:04, 7.21M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  16%|▍  | 5.56M/33.8M [00:00<00:03, 8.05M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  23%|▋  | 7.95M/33.8M [00:01<00:03, 7.11M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  29%|▊  | 9.77M/33.8M [00:01<00:02, 8.49M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  35%|█  | 11.7M/33.8M [00:01<00:02, 7.83M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  39%|█▏ | 13.3M/33.8M [00:01<00:02, 9.10M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  46%|█▍ | 15.5M/33.8M [00:01<00:01, 9.74M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  50%|█▌ | 17.0M/33.8M [00:01<00:01, 8.70M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  58%|█▋ | 19.7M/33.8M [00:02<00:01, 8.62M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  64%|█▉ | 21.8M/33.8M [00:02<00:01, 8.95M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  69%|██ | 23.3M/33.8M [00:02<00:01, 10.0M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  75%|██▎| 25.4M/33.8M [00:02<00:00, 9.92M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  80%|██▍| 27.2M/33.8M [00:03<00:00, 9.46M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  87%|██▌| 29.3M/33.8M [00:03<00:00, 9.64M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  93%|██▊| 31.4M/33.8M [00:03<00:00, 9.86M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  99%|██▉| 33.4M/33.8M [00:03<00:00, 9.74M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/33.8M [00:00<?, ? Bytes/s]
Total:  99%|█████████████████████████▋| 2.15G/2.17G [04:17<00:02, 8.34M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/12.9M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:  11%|▎  | 1.47M/12.9M [00:00<00:00, 14.5M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  34%|█  | 4.40M/12.9M [00:00<00:00, 10.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  45%|█▎ | 5.79M/12.9M [00:00<00:00, 11.1M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  69%|██ | 8.94M/12.9M [00:00<00:00, 10.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  81%|██▍| 10.5M/12.9M [00:00<00:00, 11.4M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/12.9M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/11.2M [00:00<?, ? Bytes/s]

Get sub-04/s .. _bold.nii.gz:  26%|▊  | 2.95M/11.2M [00:00<00:00, 14.7M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  40%|█▏ | 4.51M/11.2M [00:00<00:00, 10.6M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  53%|█▌ | 5.91M/11.2M [00:00<00:00, 11.6M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  74%|██▏| 8.29M/11.2M [00:00<00:00, 11.5M Bytes/s]

Get sub-04/s .. _bold.nii.gz:  97%|██▉| 10.9M/11.2M [00:00<00:00, 11.8M Bytes/s]

Get sub-04/s .. _bold.nii.gz:   0%|            | 0.00/11.2M [00:00<?, ? Bytes/s]

get(ok): sub-01/ses-retest/anat/sub-01_ses-retest_T1w.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-retest/dwi/sub-01_ses-retest_dwi.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-retest/func/sub-01_ses-retest_task-covertverbgeneration_bold.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-retest/func/sub-01_ses-retest_task-fingerfootlips_bold.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-retest/func/sub-01_ses-retest_task-linebisection_bold.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-retest/func/sub-01_ses-retest_task-overtverbgeneration_bold.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-retest/func/sub-01_ses-retest_task-overtwordrepetition_bold.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-test/anat/sub-01_ses-test_T1w.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-test/dwi/sub-01_ses-test_dwi.nii.gz (file) [from s3-PUBLIC...]
get(ok): sub-01/ses-test/func/sub-01_ses-test_task-covertverbgeneration_bold.nii.gz (file) [from s3-PUBLIC...]
  [60 similar messages have been suppressed; disable with datalad.ui.suppress-similar-results=off]
get(ok): sub-01 (directory)
get(ok): sub-02 (directory)
get(ok): sub-05 (directory)
get(ok): sub-03 (directory)
get(ok): sub-04 (directory)
action summary:
  get (ok: 75)

In [3]:
!tree -L 4 ds000114

ds000114
├── CHANGES
├── dataset_description.json
├── dwi.bval
├── dwi.bvec
├── participants.tsv
├── sub-01
│   ├── ses-retest
│   │   ├── anat
│   │   │   └── sub-01_ses-retest_T1w.nii.gz -> ../../../.git/annex/objects/xm/25/MD5E-s8503839--3b3b49b2396b59ddd5a73b7f596f9e46.nii.gz/MD5E-s8503839--3b3b49b2396b59ddd5a73b7f596f9e46.nii.gz
│   │   ├── dwi
│   │   │   └── sub-01_ses-retest_dwi.nii.gz -> ../../../.git/annex/objects/0K/16/MD5E-s99899518--5ebac8e9e23180638dd68dde10b818be.nii.gz/MD5E-s99899518--5ebac8e9e23180638dd68dde10b818be.nii.gz
│   │   └── func
│   │       ├── sub-01_ses-retest_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/3q/Qf/MD5E-s22317848--b30f5b2f7a6039a3e384bcb40bec7e55.nii.gz/MD5E-s22317848--b30f5b2f7a6039a3e384bcb40bec7e55.nii.gz
│   │       ├── sub-01_ses-retest_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/26/6j/MD5E-s23793248--327e42d440f0557105bf7c05a3b9f1e8.nii.gz/MD5E-s23793248--327e42d440f0557105bf7c05a3b9f1e8.nii.gz
│   │       ├── sub-01_ses-retest_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/qv/gf/MD5E-s30728838--58392e3ead9caeefe148a57c71dd5b44.nii.gz/MD5E-s30728838--58392e3ead9caeefe148a57c71dd5b44.nii.gz
│   │       ├── sub-01_ses-retest_task-linebisection_events.tsv
│   │       ├── sub-01_ses-retest_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/Fx/6K/MD5E-s11839146--5f62c005467de0dabc6ebcd09c3e7ec3.nii.gz/MD5E-s11839146--5f62c005467de0dabc6ebcd09c3e7ec3.nii.gz
│   │       └── sub-01_ses-retest_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/x3/qW/MD5E-s10162063--a86a0f448872de33a901a6b639e975c9.nii.gz/MD5E-s10162063--a86a0f448872de33a901a6b639e975c9.nii.gz
│   └── ses-test
│       ├── anat
│       │   └── sub-01_ses-test_T1w.nii.gz -> ../../../.git/annex/objects/QP/jm/MD5E-s8677710--d6820f6cb8fb965e864419c14f6a22d5.nii.gz/MD5E-s8677710--d6820f6cb8fb965e864419c14f6a22d5.nii.gz
│       ├── dwi
│       │   └── sub-01_ses-test_dwi.nii.gz -> ../../../.git/annex/objects/X2/kJ/MD5E-s104193417--454850ac9ed1c96c40b6b7946e51bf71.nii.gz/MD5E-s104193417--454850ac9ed1c96c40b6b7946e51bf71.nii.gz
│       └── func
│           ├── sub-01_ses-test_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/mx/zJ/MD5E-s22944165--71b1eda077a1003a177552f6c380323a.nii.gz/MD5E-s22944165--71b1eda077a1003a177552f6c380323a.nii.gz
│           ├── sub-01_ses-test_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/k6/4f/MD5E-s24454931--e9ab535d84a922b0c7ed52461244cf47.nii.gz/MD5E-s24454931--e9ab535d84a922b0c7ed52461244cf47.nii.gz
│           ├── sub-01_ses-test_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/32/Qq/MD5E-s31617092--151bc230c3b577110883369b6fad0daa.nii.gz/MD5E-s31617092--151bc230c3b577110883369b6fad0daa.nii.gz
│           ├── sub-01_ses-test_task-linebisection_events.tsv
│           ├── sub-01_ses-test_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/p3/fZ/MD5E-s12048980--648c9094579aa5d047a5f6db468f9bc9.nii.gz/MD5E-s12048980--648c9094579aa5d047a5f6db468f9bc9.nii.gz
│           └── sub-01_ses-test_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/56/GV/MD5E-s10362270--6a5c483d118db28ff8a62455def5501c.nii.gz/MD5E-s10362270--6a5c483d118db28ff8a62455def5501c.nii.gz
├── sub-02
│   ├── ses-retest
│   │   ├── anat
│   │   │   └── sub-02_ses-retest_T1w.nii.gz -> ../../../.git/annex/objects/VV/x2/MD5E-s8901003--6ad41304cbd57904227d914c054dcdc3.nii.gz/MD5E-s8901003--6ad41304cbd57904227d914c054dcdc3.nii.gz
│   │   ├── dwi
│   │   │   └── sub-02_ses-retest_dwi.nii.gz -> ../../../.git/annex/objects/ZZ/4X/MD5E-s101314358--9be934908a88073bc070e524651ee665.nii.gz/MD5E-s101314358--9be934908a88073bc070e524651ee665.nii.gz
│   │   └── func
│   │       ├── sub-02_ses-retest_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/vk/gK/MD5E-s22730907--26df7900a64e1d9f90e17ad0fa53145d.nii.gz/MD5E-s22730907--26df7900a64e1d9f90e17ad0fa53145d.nii.gz
│   │       ├── sub-02_ses-retest_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/Jg/vq/MD5E-s24364271--593256c66ce88ed8aaef140a4b37c6ec.nii.gz/MD5E-s24364271--593256c66ce88ed8aaef140a4b37c6ec.nii.gz
│   │       ├── sub-02_ses-retest_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/pZ/GJ/MD5E-s31238024--929a3999fa92002e571bec60f7343b65.nii.gz/MD5E-s31238024--929a3999fa92002e571bec60f7343b65.nii.gz
│   │       ├── sub-02_ses-retest_task-linebisection_events.tsv
│   │       ├── sub-02_ses-retest_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/35/2V/MD5E-s12039294--070d0299974f916bdee0791985381593.nii.gz/MD5E-s12039294--070d0299974f916bdee0791985381593.nii.gz
│   │       └── sub-02_ses-retest_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/Z4/0G/MD5E-s10369674--71d655f61e4ce98ae7761ce76e3c30f9.nii.gz/MD5E-s10369674--71d655f61e4ce98ae7761ce76e3c30f9.nii.gz
│   └── ses-test
│       ├── anat
│       │   └── sub-02_ses-test_T1w.nii.gz -> ../../../.git/annex/objects/qq/gm/MD5E-s10025785--0e790e210a275d76e3f2f4d895df6358.nii.gz/MD5E-s10025785--0e790e210a275d76e3f2f4d895df6358.nii.gz
│       ├── dwi
│       │   └── sub-02_ses-test_dwi.nii.gz -> ../../../.git/annex/objects/8x/vp/MD5E-s104222416--86575d07809e9c717079592a12c69344.nii.gz/MD5E-s104222416--86575d07809e9c717079592a12c69344.nii.gz
│       └── func
│           ├── sub-02_ses-test_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/F6/6J/MD5E-s23349944--2a2b8bc1f3d90e84d879bdd4638103c8.nii.gz/MD5E-s23349944--2a2b8bc1f3d90e84d879bdd4638103c8.nii.gz
│           ├── sub-02_ses-test_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/pG/k1/MD5E-s24882575--75c39bee9e25e02c629dfcce1b378589.nii.gz/MD5E-s24882575--75c39bee9e25e02c629dfcce1b378589.nii.gz
│           ├── sub-02_ses-test_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/WM/m9/MD5E-s32248732--4cd877de7b4c66e073610dffb67dfbcc.nii.gz/MD5E-s32248732--4cd877de7b4c66e073610dffb67dfbcc.nii.gz
│           ├── sub-02_ses-test_task-linebisection_events.tsv
│           ├── sub-02_ses-test_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/Jz/zM/MD5E-s12348374--67f259c7e0bbb0fe39e747be5f905a4b.nii.gz/MD5E-s12348374--67f259c7e0bbb0fe39e747be5f905a4b.nii.gz
│           └── sub-02_ses-test_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/6g/Zw/MD5E-s10496422--bae24132d514bb028ca8a3d749363bd9.nii.gz/MD5E-s10496422--bae24132d514bb028ca8a3d749363bd9.nii.gz
├── sub-03
│   ├── ses-retest
│   │   ├── anat
│   │   │   └── sub-03_ses-retest_T1w.nii.gz -> ../../../.git/annex/objects/64/vk/MD5E-s8125470--75575589e60ce58d95b4d72d3b4bf222.nii.gz/MD5E-s8125470--75575589e60ce58d95b4d72d3b4bf222.nii.gz
│   │   ├── dwi
│   │   │   └── sub-03_ses-retest_dwi.nii.gz -> ../../../.git/annex/objects/Pf/07/MD5E-s101660442--50491e142880d5f32b6c33cde372fb05.nii.gz/MD5E-s101660442--50491e142880d5f32b6c33cde372fb05.nii.gz
│   │   └── func
│   │       ├── sub-03_ses-retest_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/z1/0p/MD5E-s22709259--a01b5167228be96f007e84bab43e8b60.nii.gz/MD5E-s22709259--a01b5167228be96f007e84bab43e8b60.nii.gz
│   │       ├── sub-03_ses-retest_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/WG/k5/MD5E-s24175561--769ba7da6cac3318c47bc9215a77359b.nii.gz/MD5E-s24175561--769ba7da6cac3318c47bc9215a77359b.nii.gz
│   │       ├── sub-03_ses-retest_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/Qf/QX/MD5E-s31217356--89a8e84fbe0b5f019ce69d4ad643863c.nii.gz/MD5E-s31217356--89a8e84fbe0b5f019ce69d4ad643863c.nii.gz
│   │       ├── sub-03_ses-retest_task-linebisection_events.tsv
│   │       ├── sub-03_ses-retest_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/Xx/q2/MD5E-s11992800--894dac07de9c8cddf6ea7e42f39f5c80.nii.gz/MD5E-s11992800--894dac07de9c8cddf6ea7e42f39f5c80.nii.gz
│   │       └── sub-03_ses-retest_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/7F/8p/MD5E-s10359493--9b3e5cc9933645901049c64c600ec6ca.nii.gz/MD5E-s10359493--9b3e5cc9933645901049c64c600ec6ca.nii.gz
│   └── ses-test
│       ├── anat
│       │   └── sub-03_ses-test_T1w.nii.gz -> ../../../.git/annex/objects/P9/kj/MD5E-s7970968--75bb38265ea96864bfa0b012ba21b0b0.nii.gz/MD5E-s7970968--75bb38265ea96864bfa0b012ba21b0b0.nii.gz
│       ├── dwi
│       │   └── sub-03_ses-test_dwi.nii.gz -> ../../../.git/annex/objects/F3/Pf/MD5E-s106544064--badea2659bd4440ff4c20e2f149034cc.nii.gz/MD5E-s106544064--badea2659bd4440ff4c20e2f149034cc.nii.gz
│       └── func
│           ├── sub-03_ses-test_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/J6/f0/MD5E-s23145742--a792c0592cb77a161eb5d000a618c17c.nii.gz/MD5E-s23145742--a792c0592cb77a161eb5d000a618c17c.nii.gz
│           ├── sub-03_ses-test_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/gp/QM/MD5E-s24520513--0fd08e07bbee37ac9efe14c7b265299a.nii.gz/MD5E-s24520513--0fd08e07bbee37ac9efe14c7b265299a.nii.gz
│           ├── sub-03_ses-test_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/mP/mg/MD5E-s31785134--76856b9d6c90730144196aa48e4d9a9f.nii.gz/MD5E-s31785134--76856b9d6c90730144196aa48e4d9a9f.nii.gz
│           ├── sub-03_ses-test_task-linebisection_events.tsv
│           ├── sub-03_ses-test_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/w3/XQ/MD5E-s12159084--67f84031d332467dae91107e53f0d89e.nii.gz/MD5E-s12159084--67f84031d332467dae91107e53f0d89e.nii.gz
│           └── sub-03_ses-test_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/Qk/kK/MD5E-s10552089--e00b7544d9c44dddcd966e2c1dcd468f.nii.gz/MD5E-s10552089--e00b7544d9c44dddcd966e2c1dcd468f.nii.gz
├── sub-04
│   ├── ses-retest
│   │   ├── anat
│   │   │   └── sub-04_ses-retest_T1w.nii.gz -> ../../../.git/annex/objects/z9/V6/MD5E-s10125819--92fcdbdd50bb334651e474417237a7f2.nii.gz/MD5E-s10125819--92fcdbdd50bb334651e474417237a7f2.nii.gz
│   │   ├── dwi
│   │   │   └── sub-04_ses-retest_dwi.nii.gz -> ../../../.git/annex/objects/0Q/z6/MD5E-s102315940--827455ba66acecb6a2c8b9222bcd9fa1.nii.gz/MD5E-s102315940--827455ba66acecb6a2c8b9222bcd9fa1.nii.gz
│   │   └── func
│   │       ├── sub-04_ses-retest_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/6G/PV/MD5E-s24644977--c2411e3bad71cddeb2c083f999d22f93.nii.gz/MD5E-s24644977--c2411e3bad71cddeb2c083f999d22f93.nii.gz
│   │       ├── sub-04_ses-retest_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/Jf/m1/MD5E-s26197435--1ec999d21c0039897b67f38f5870d70c.nii.gz/MD5E-s26197435--1ec999d21c0039897b67f38f5870d70c.nii.gz
│   │       ├── sub-04_ses-retest_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/J2/v9/MD5E-s33748727--044de5969956d86b7cdee0eb36e26c9e.nii.gz/MD5E-s33748727--044de5969956d86b7cdee0eb36e26c9e.nii.gz
│   │       ├── sub-04_ses-retest_task-linebisection_events.tsv
│   │       ├── sub-04_ses-retest_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/Kf/5K/MD5E-s12862957--a356882c1f18391f2f5215bda39f817f.nii.gz/MD5E-s12862957--a356882c1f18391f2f5215bda39f817f.nii.gz
│   │       └── sub-04_ses-retest_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/70/k3/MD5E-s11172082--dcd559966a66e0645cb98a9b13c67a6c.nii.gz/MD5E-s11172082--dcd559966a66e0645cb98a9b13c67a6c.nii.gz
│   └── ses-test
│       ├── anat
│       │   └── sub-04_ses-test_T1w.nii.gz -> ../../../.git/annex/objects/mg/5z/MD5E-s9717713--7764ef9c3fb344f69f1c2eb34cd56046.nii.gz/MD5E-s9717713--7764ef9c3fb344f69f1c2eb34cd56046.nii.gz
│       ├── dwi
│       │   └── sub-04_ses-test_dwi.nii.gz -> ../../../.git/annex/objects/W0/Gk/MD5E-s104883316--ec0aec8977aa5a5c0901cd9d2e25347c.nii.gz/MD5E-s104883316--ec0aec8977aa5a5c0901cd9d2e25347c.nii.gz
│       └── func
│           ├── sub-04_ses-test_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/GX/QK/MD5E-s24677139--d835385cb69d9907d6b0cb7311a91ff3.nii.gz/MD5E-s24677139--d835385cb69d9907d6b0cb7311a91ff3.nii.gz
│           ├── sub-04_ses-test_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/Qv/qX/MD5E-s26270785--61f837b1ef1f667975ab25b820844d93.nii.gz/MD5E-s26270785--61f837b1ef1f667975ab25b820844d93.nii.gz
│           ├── sub-04_ses-test_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/gk/3p/MD5E-s33823763--377e091ada8819942070a374b71ea986.nii.gz/MD5E-s33823763--377e091ada8819942070a374b71ea986.nii.gz
│           ├── sub-04_ses-test_task-linebisection_events.tsv
│           ├── sub-04_ses-test_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/0Q/jG/MD5E-s12907201--46e3c39a8f7ec6c2f5b1ab157efa10d1.nii.gz/MD5E-s12907201--46e3c39a8f7ec6c2f5b1ab157efa10d1.nii.gz
│           └── sub-04_ses-test_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/X5/FJ/MD5E-s11171792--bc9ba9ef24fcf364f3057401c17b1c49.nii.gz/MD5E-s11171792--bc9ba9ef24fcf364f3057401c17b1c49.nii.gz
├── sub-05
│   ├── ses-retest
│   │   ├── anat
│   │   │   └── sub-05_ses-retest_T1w.nii.gz -> ../../../.git/annex/objects/JK/PV/MD5E-s9511479--cec6ad961369ea1b21521d33040406d1.nii.gz/MD5E-s9511479--cec6ad961369ea1b21521d33040406d1.nii.gz
│   │   ├── dwi
│   │   │   └── sub-05_ses-retest_dwi.nii.gz -> ../../../.git/annex/objects/Mx/KM/MD5E-s104024235--7a107b0b7d70f0e0a60e5fccbda23f41.nii.gz/MD5E-s104024235--7a107b0b7d70f0e0a60e5fccbda23f41.nii.gz
│   │   └── func
│   │       ├── sub-05_ses-retest_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/x3/7x/MD5E-s24240966--89dc3e4888f5788e390be04cc91565ef.nii.gz/MD5E-s24240966--89dc3e4888f5788e390be04cc91565ef.nii.gz
│   │       ├── sub-05_ses-retest_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/V4/fV/MD5E-s25998505--071b1bd89a8d245b7a7a23323b434706.nii.gz/MD5E-s25998505--071b1bd89a8d245b7a7a23323b434706.nii.gz
│   │       ├── sub-05_ses-retest_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/3v/1w/MD5E-s33598359--952f5c8625b962a9f5ccb3d2bb58d1aa.nii.gz/MD5E-s33598359--952f5c8625b962a9f5ccb3d2bb58d1aa.nii.gz
│   │       ├── sub-05_ses-retest_task-linebisection_events.tsv
│   │       ├── sub-05_ses-retest_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/w0/75/MD5E-s12942731--e26171327d6bbdd4f392e1e327f92850.nii.gz/MD5E-s12942731--e26171327d6bbdd4f392e1e327f92850.nii.gz
│   │       └── sub-05_ses-retest_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/2V/K8/MD5E-s11109819--e0875ced4e44d9a144316893937a063b.nii.gz/MD5E-s11109819--e0875ced4e44d9a144316893937a063b.nii.gz
│   └── ses-test
│       ├── anat
│       │   └── sub-05_ses-test_T1w.nii.gz -> ../../../.git/annex/objects/f1/XP/MD5E-s9942928--e32c1d5fb1d6db6449b19be10b5efc67.nii.gz/MD5E-s9942928--e32c1d5fb1d6db6449b19be10b5efc67.nii.gz
│       ├── dwi
│       │   └── sub-05_ses-test_dwi.nii.gz -> ../../../.git/annex/objects/q3/gK/MD5E-s108049676--0d107c0acf9bed884baedfb7bc6a76e7.nii.gz/MD5E-s108049676--0d107c0acf9bed884baedfb7bc6a76e7.nii.gz
│       └── func
│           ├── sub-05_ses-test_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/0z/1V/MD5E-s24924488--f11c9aec356aa58e53e7a154222f4e74.nii.gz/MD5E-s24924488--f11c9aec356aa58e53e7a154222f4e74.nii.gz
│           ├── sub-05_ses-test_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/GK/P9/MD5E-s26693258--a904caebfaa372a21eb37231bae55299.nii.gz/MD5E-s26693258--a904caebfaa372a21eb37231bae55299.nii.gz
│           ├── sub-05_ses-test_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/jW/X3/MD5E-s34416273--467b8d34b985d8caa2ac26e93506b775.nii.gz/MD5E-s34416273--467b8d34b985d8caa2ac26e93506b775.nii.gz
│           ├── sub-05_ses-test_task-linebisection_events.tsv
│           ├── sub-05_ses-test_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/fZ/Qx/MD5E-s13124683--f6b7dbf08272097300cf977ddc06a3a3.nii.gz/MD5E-s13124683--f6b7dbf08272097300cf977ddc06a3a3.nii.gz
│           └── sub-05_ses-test_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/wP/ZP/MD5E-s11526323--f99a4f1f281cc1213c556b1f446724e5.nii.gz/MD5E-s11526323--f99a4f1f281cc1213c556b1f446724e5.nii.gz
├── sub-06
│   ├── ses-retest
│   │   ├── anat
│   │   │   └── sub-06_ses-retest_T1w.nii.gz -> ../../../.git/annex/objects/9W/pF/MD5E-s9712028--b4fbccf8add0667a4cba4306d2609bf6.nii.gz/MD5E-s9712028--b4fbccf8add0667a4cba4306d2609bf6.nii.gz
│   │   ├── dwi
│   │   │   └── sub-06_ses-retest_dwi.nii.gz -> ../../../.git/annex/objects/82/0m/MD5E-s102946238--20e290d95ed62fe68f5c73c3e057aa68.nii.gz/MD5E-s102946238--20e290d95ed62fe68f5c73c3e057aa68.nii.gz
│   │   └── func
│   │       ├── sub-06_ses-retest_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/KQ/41/MD5E-s24361814--23edea0b5a1c7b770ae89a700099482a.nii.gz/MD5E-s24361814--23edea0b5a1c7b770ae89a700099482a.nii.gz
│   │       ├── sub-06_ses-retest_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/MW/2q/MD5E-s26020756--5525a120e543de5a7c561eb0ac058c50.nii.gz/MD5E-s26020756--5525a120e543de5a7c561eb0ac058c50.nii.gz
│   │       ├── sub-06_ses-retest_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/kz/g4/MD5E-s33607078--55b31ff735c4a5d571e49ca0fa44ef3b.nii.gz/MD5E-s33607078--55b31ff735c4a5d571e49ca0fa44ef3b.nii.gz
│   │       ├── sub-06_ses-retest_task-linebisection_events.tsv
│   │       ├── sub-06_ses-retest_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/qf/92/MD5E-s12884913--85e85fa3810ffbc274163169994516ce.nii.gz/MD5E-s12884913--85e85fa3810ffbc274163169994516ce.nii.gz
│   │       └── sub-06_ses-retest_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/zx/Mx/MD5E-s11071105--d4dc6401799624f330849cb2a26ecce0.nii.gz/MD5E-s11071105--d4dc6401799624f330849cb2a26ecce0.nii.gz
│   └── ses-test
│       ├── anat
│       │   └── sub-06_ses-test_T1w.nii.gz -> ../../../.git/annex/objects/gm/9z/MD5E-s10429286--0dcb4734fa4f0bccc2f7b953e630e24d.nii.gz/MD5E-s10429286--0dcb4734fa4f0bccc2f7b953e630e24d.nii.gz
│       ├── dwi
│       │   └── sub-06_ses-test_dwi.nii.gz -> ../../../.git/annex/objects/q4/Jf/MD5E-s111500846--b91fca5d1ca3b959becfc5da8923aab1.nii.gz/MD5E-s111500846--b91fca5d1ca3b959becfc5da8923aab1.nii.gz
│       └── func
│           ├── sub-06_ses-test_task-covertverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/K1/PM/MD5E-s25380586--d07bdf55b059b9532106bdf96c3d5be6.nii.gz/MD5E-s25380586--d07bdf55b059b9532106bdf96c3d5be6.nii.gz
│           ├── sub-06_ses-test_task-fingerfootlips_bold.nii.gz -> ../../../.git/annex/objects/V9/52/MD5E-s26868014--5c133cbc6d656f72433b1c5da1ea66e7.nii.gz/MD5E-s26868014--5c133cbc6d656f72433b1c5da1ea66e7.nii.gz
│           ├── sub-06_ses-test_task-linebisection_bold.nii.gz -> ../../../.git/annex/objects/x0/Z9/MD5E-s34846203--cd71c6d597806515b0f8b956637c33a1.nii.gz/MD5E-s34846203--cd71c6d597806515b0f8b956637c33a1.nii.gz
│           ├── sub-06_ses-test_task-linebisection_events.tsv
│           ├── sub-06_ses-test_task-overtverbgeneration_bold.nii.gz -> ../../../.git/annex/objects/KV/31/MD5E-s13292168--c6397d91154050fe59a42da6316b0d4b.nii.gz/MD5E-s13292168--c6397d91154050fe59a42da6316b0d4b.nii.gz
│           └── sub-06_ses-test_task-overtwordrepetition_bold.nii.gz -> ../../../.git/annex/objects/6K/wQ/MD5E-s11225007--3a39708bd39fa2e4fadccbbf3056bb4e.nii.gz/MD5E-s11225007--3a39708bd39fa2e4fadccbbf3056bb4e.nii.gz
├── sub-07
│   ├── ses-retest
│   │   ├── anat
│   │   │   └── sub-07_ses-retest_T1w.nii.gz -> ../../../.git/annex/objects/wz/fx/MD5E-s8725991--d2be2d444bca2a33e53521f5aa9fafaa.nii.gz/MD5E-s8725991--d2be2d444bca2a33e53521f5aa9fafaa.nii.gz
│   │   ├── dwi
│   │   │   └── sub-07_ses-retest_dwi.nii.gz -> ../../../.git/annex/objects/wP/wJ/MD5E-s101870616--440ae52ddacae1affe2e1f59ac795dd3.nii.gz/MD5E-s101870616--440ae52ddacae1affe2e1f59ac795dd3.nii.gz
│   │   └── func

## Querying BIDS datasets

### Loading BIDS datasets
The BIDSLayout instance is a lightweight container for all of the files in the BIDS project directory. It automatically detects any BIDS entities found in the file paths, and allows us to perform simple but relatively powerful queries over the file tree. By default, defined BIDS entities include things like “subject”, “session”, “run”, and “type”.

In [4]:
from bids.layout import BIDSLayout
layout = BIDSLayout("ds000114")

### Querying the ```BIDSLayout``` using ```get```

When a BIDSLayout is initialized, it scans and indexes all files and metadata within the specified root directory.  Once the indexing is complete, you can start exploring the dataset through different types of queries. The main method for this is ```.get()```. If you call ```.get()``` without any arguments, it simply returns a list of all BIDS files in the dataset:

In [5]:
all_files = layout.get()
print("There are {} files in the layout.".format(len(all_files)))
print("\nThe first 3 files are:")
all_files[:3]

There are 174 files in the layout.

The first 3 files are:

[<BIDSFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/CHANGES'>,
 <BIDSJSONFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/dataset_description.json'>,
 <BIDSFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/dwi.bval'>]

In this Python list, each element is a BIDSFile object. If you want to work with just file names, you can simpliy it with:

In [6]:
layout.get(return_type='filename')[:3]

['/home/jovyan/workspace/books/examples/workflows/ds000114/CHANGES',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/dataset_description.json',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/dwi.bval']

__Common BIDS Entities:__

The ```.get()```method supports various arguments that let us narrow down the results based on specific criteria. Any BIDS-defined keywords - referred to as entities in PyBIDS - can be used as filters. Here are the most common ones:

```suffix```: The part of a BIDS filename just before the extension (e.g., 'bold', 'events', 'physio', etc.).

```subject```: The subject label

```session```: The session label

```run```: The run index

```task```: The task name

In [7]:
layout.get_entities()

{'subject': <Entity subject (pattern=[/\\]+sub-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'session': <Entity session (pattern=[_/\\]+ses-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'sample': <Entity sample (pattern=[_/\\]+sample-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'task': <Entity task (pattern=[_/\\]+task-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'tracksys': <Entity tracksys (pattern=[_/\\]+tracksys-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'acquisition': <Entity acquisition (pattern=[_/\\]+acq-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'nucleus': <Entity nucleus (pattern=[_/\\]+nuc-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'volume': <Entity volume (pattern=[_/\\]+voi-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'ceagent': <Entity ceagent (pattern=[_/\\]+ce-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'staining': <Entity staining (pattern=[_/\\]+stain-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'tracer': <Entity tracer (pattern=[_/\\]+trc-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'reconstruction': <Entity reconstruction (pattern=[_/\\]+rec-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'direction': <Entity direction (pattern=[_/\\]+dir-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'run': <Entity run (pattern=[_/\\]+run-(\d+), dtype=<class 'bids.layout.utils.PaddedInt'>)>,
 'proc': <Entity proc (pattern=[_/\\]+proc-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'modality': <Entity modality (pattern=[_/\\]+mod-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'echo': <Entity echo (pattern=[_/\\]+echo-([0-9]+), dtype=<class 'str'>)>,
 'flip': <Entity flip (pattern=[_/\\]+flip-([0-9]+), dtype=<class 'str'>)>,
 'inv': <Entity inv (pattern=[_/\\]+inv-([0-9]+), dtype=<class 'str'>)>,
 'mt': <Entity mt (pattern=[_/\\]+mt-(on|off), dtype=<class 'str'>)>,
 'part': <Entity part (pattern=[_/\\]+part-(imag|mag|phase|real), dtype=<class 'str'>)>,
 'recording': <Entity recording (pattern=[_/\\]+recording-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'space': <Entity space (pattern=[_/\\]+space-([a-zA-Z0-9+]+), dtype=<class 'str'>)>,
 'chunk': <Entity chunk (pattern=[_/\\]+chunk-([0-9]+), dtype=<class 'str'>)>,
 'suffix': <Entity suffix (pattern=(?:^|[_/\\])([a-zA-Z0-9+]+)\.[^/\\]+$, dtype=<class 'str'>)>,
 'scans': <Entity scans (pattern=(.*\_scans.tsv)$, dtype=<class 'str'>)>,
 'fmap': <Entity fmap (pattern=(phasediff|magnitude[1-2]|phase[1-2]|fieldmap|epi)\.nii, dtype=<class 'str'>)>,
 'datatype': <Entity datatype (pattern=[/\\]+(anat|beh|dwi|eeg|fmap|func|ieeg|meg|micr|motion|mrs|nirs|perf|pet)[/\\]+, dtype=<class 'str'>)>,
 'extension': <Entity extension (pattern=[^./\\](\.[^/\\]+)$, dtype=<class 'str'>)>,
 'EchoTime': <Entity EchoTime (pattern=None, dtype=<class 'str'>)>,
 'FlipAngle': <Entity FlipAngle (pattern=None, dtype=<class 'str'>)>,
 'RepetitionTime': <Entity RepetitionTime (pattern=None, dtype=<class 'str'>)>,
 'SliceTiming': <Entity SliceTiming (pattern=None, dtype=<class 'str'>)>,
 'TaskName': <Entity TaskName (pattern=None, dtype=<class 'str'>)>}

*Query by subjects:*

In [8]:
layout.get_subjects()

['01', '02', '03', '04', '05', '06', '07', '08', '09', '10']

*Query by sessions:*

In [9]:
layout.get_sessions()

['retest', 'test']

*Query by tasks:*

In [10]:
layout.get_task()

['covertverbgeneration',
 'fingerfootlips',
 'linebisection',
 'overtverbgeneration',
 'overtwordrepetition']

Here’s how we would retrieve all BOLD runs with *.nii.gz* extensions for *subject '02'*:

In [11]:
# Retrieve filenames of all BOLD runs for subject 02
layout.get(subject='02', extension='nii.gz', suffix='bold', return_type='filename')

['/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-retest/func/sub-02_ses-retest_task-covertverbgeneration_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-retest/func/sub-02_ses-retest_task-fingerfootlips_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-retest/func/sub-02_ses-retest_task-linebisection_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-retest/func/sub-02_ses-retest_task-overtverbgeneration_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-retest/func/sub-02_ses-retest_task-overtwordrepetition_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-covertverbgeneration_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-fingerfootlips_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-linebisection_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-overtverbgeneration_bold.nii.gz',
 '/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-overtwordrepetition_bold.nii.gz']

### Extracting metadata
All the entities mentioned above are derived from the filenames in a BIDS dataset. However, sometimes we want to filter files not just by their names, but also using **metadata** defined in sidecar JSON files, as specified by the BIDS standard. When a BIDSLayout is initialized, it automatically indexes all associated metadata files. This means we can use any key found in a JSON file as a filter in ```.get()```, and we can even combine these with core BIDS entities like subject, run, and task.

For example, suppose we want to retrieve all files that meet the following criteria:
(a) the RepetitionTime metadata value is 2.5,
(b) the task is either 'covert_verb_generation' or 'finger_foot_lips', and
(c) the subject is '01' or '02'.

Here’s how we can do that:

In [12]:
layout.get(subject=['01', '02'], RepetitionTime=2.5, TaskName=['covert_verb_generation', 'finger_foot_lips'] )

[<BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-01/ses-retest/func/sub-01_ses-retest_task-covertverbgeneration_bold.nii.gz'>,
 <BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-01/ses-retest/func/sub-01_ses-retest_task-fingerfootlips_bold.nii.gz'>,
 <BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-01/ses-test/func/sub-01_ses-test_task-covertverbgeneration_bold.nii.gz'>,
 <BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-01/ses-test/func/sub-01_ses-test_task-fingerfootlips_bold.nii.gz'>,
 <BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-retest/func/sub-02_ses-retest_task-covertverbgeneration_bold.nii.gz'>,
 <BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-retest/func/sub-02_ses-retest_task-fingerfootlips_bold.nii.gz'>,
 <BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-covertverbgeneration_bold.nii.gz'>,
 <BIDSImageFile filename='/home/jovyan/workspace/books/examples/workflows/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-fingerfootlips_bold.nii.gz'>]

## The ```BIDSFile```

Calling ```.get()``` on a ```BIDSLayout``` returns a list of ```BIDSFile``` objects by default. These are lightweight representations of individual files within a BIDS dataset and offer convenient access to various attributes and methods. Let’s explore what a ```BIDSFile``` can do. To start, we’ll select a random file from the layout.

In [13]:
# Pick the 11th file in the dataset
bf = layout.get()[11]

# Print it
bf

A ```BIDSFile``` provides a convenient interface to interact with individual files in a BIDS dataset. Depending on the file type, different attributes and methods are available. Keep in mind that some methods are only applicable to specific types of files—for example, you can’t use ```.get_image()``` on a non-image file.

Here are some commonly used attributes and methods:

```.path``` – Full path to the file

```.filename``` – Name of the file (excluding the directory)

```.dirname``` – Directory where the file is located

```.get_entities()``` – Returns a dictionary of entities (e.g., subject, task) associated with the file; metadata can be optionally included

```.get_image()``` – Loads the file as a nibabel image (only valid for image files)

```.get_df()``` – Loads the file into a pandas DataFrame (works for .tsv files)

```.get_metadata()``` – Retrieves a dictionary of metadata from the related JSON sidecar(s)

```.get_associations()``` – Lists other files that are linked to this one (e.g., JSON, events, or anatomical associations)

In [14]:
# Print all the entities associated with this file, and their values
bf.get_entities()

{'datatype': 'func',
 'extension': '.nii.gz',
 'session': 'retest',
 'subject': '01',
 'suffix': 'bold',
 'task': 'overtverbgeneration'}

In [15]:
# Print all metadata of this file
bf.get_metadata()

{'EchoTime': 0.05,
 'FlipAngle': 90,
 'RepetitionTime': 5.0,
 'SliceTiming': [0.0,
  1.2499999999999998,
  0.08333333333333333,
  1.333333333333333,
  0.16666666666666666,
  1.4166666666666663,
  0.25,
  1.4999999999999996,
  0.3333333333333333,
  1.5833333333333328,
  0.41666666666666663,
  1.666666666666666,
  0.5,
  1.7499999999999993,
  0.5833333333333333,
  1.8333333333333326,
  0.6666666666666666,
  1.9166666666666659,
  0.75,
  1.9999999999999991,
  0.8333333333333333,
  2.083333333333332,
  0.9166666666666666,
  2.1666666666666656,
  1.0,
  2.249999999999999,
  1.0833333333333333,
  2.333333333333332,
  1.1666666666666665,
  2.416666666666665],
 'TaskName': 'overt_verb_generation'}

In [16]:
# Get union of both of the above in one shot like this
bf.get_entities(metadata='all')

{'EchoTime': 0.05,
 'FlipAngle': 90,
 'RepetitionTime': 5.0,
 'SliceTiming': [0.0,
  1.2499999999999998,
  0.08333333333333333,
  1.333333333333333,
  0.16666666666666666,
  1.4166666666666663,
  0.25,
  1.4999999999999996,
  0.3333333333333333,
  1.5833333333333328,
  0.41666666666666663,
  1.666666666666666,
  0.5,
  1.7499999999999993,
  0.5833333333333333,
  1.8333333333333326,
  0.6666666666666666,
  1.9166666666666659,
  0.75,
  1.9999999999999991,
  0.8333333333333333,
  2.083333333333332,
  0.9166666666666666,
  2.1666666666666656,
  1.0,
  2.249999999999999,
  1.0833333333333333,
  2.333333333333332,
  1.1666666666666665,
  2.416666666666665],
 'TaskName': 'overt_verb_generation',
 'datatype': 'func',
 'extension': '.nii.gz',
 'session': 'retest',
 'subject': '01',
 'suffix': 'bold',
 'task': 'overtverbgeneration'}

In [17]:
# Here are all the files associated with our target file in some way
bf.get_associations()

### Exporting a BIDSLayout to a pandas Dataframe
If you’re looking for a high-level overview of all the files in your BIDSLayout without manually iterating through each ```BIDSFile``` and extracting their entities, the ```.to_df()``` method offers a convenient solution. It provides a structured summary of the dataset in the form of a pandas DataFrame.

In [18]:
# Convert the layout to a pandas dataframe
df = layout.to_df()
df.head()

entity,path,datatype,extension,session,subject,suffix,task
0,/home/jovyan/workspace/books/examples/workflow...,NaN,.json,NaN,NaN,description,NaN
1,/home/jovyan/workspace/books/examples/workflow...,NaN,.bval,NaN,NaN,dwi,NaN
2,/home/jovyan/workspace/books/examples/workflow...,NaN,.bvec,NaN,NaN,dwi,NaN
3,/home/jovyan/workspace/books/examples/workflow...,NaN,.tsv,NaN,NaN,participants,NaN
4,/home/jovyan/workspace/books/examples/workflow...,anat,.nii.gz,retest,01,T1w,NaN

In [19]:
# Include metadata
layout.to_df(metadata=True).head(10)

entity,path,EchoTime,FlipAngle,RepetitionTime,SliceTiming,TaskName,datatype,extension,session,subject,suffix,task
0,/home/jovyan/workspace/books/examples/workflow...,NaN,NaN,NaN,NaN,NaN,NaN,.json,NaN,NaN,description,NaN
1,/home/jovyan/workspace/books/examples/workflow...,NaN,NaN,NaN,NaN,NaN,NaN,.bval,NaN,NaN,dwi,NaN
2,/home/jovyan/workspace/books/examples/workflow...,NaN,NaN,NaN,NaN,NaN,NaN,.bvec,NaN,NaN,dwi,NaN
3,/home/jovyan/workspace/books/examples/workflow...,NaN,NaN,NaN,NaN,NaN,NaN,.tsv,NaN,NaN,participants,NaN
4,/home/jovyan/workspace/books/examples/workflow...,NaN,NaN,NaN,NaN,NaN,anat,.nii.gz,retest,01,T1w,NaN
5,/home/jovyan/workspace/books/examples/workflow...,NaN,NaN,NaN,NaN,NaN,dwi,.nii.gz,retest,01,dwi,NaN
6,/home/jovyan/workspace/books/examples/workflow...,0.05,90,2.5,"[0.0, 1.2499999999999998, 0.08333333333333333,...",covert_verb_generation,func,.nii.gz,retest,01,bold,covertverbgeneration
7,/home/jovyan/workspace/books/examples/workflow...,0.05,90,2.5,"[0.0, 1.2499999999999998, 0.08333333333333333,...",finger_foot_lips,func,.nii.gz,retest,01,bold,fingerfootlips
8,/home/jovyan/workspace/books/examples/workflow...,0.05,90,2.5,"[0.0, 1.2499999999999998, 0.08333333333333333,...",line_bisection,func,.nii.gz,retest,01,bold,linebisection
9,/home/jovyan/workspace/books/examples/workflow...,NaN,NaN,NaN,NaN,NaN,func,.tsv,retest,01,events,linebisection

## BIDS Validator
```PyBIDS``` includes an implicit import of the ```BIDSValidator``` class from the separate ```bids-validator``` package. This class can be used to check whether a given file path conforms to BIDS naming conventions and to infer what type of data the file represents.

However, it's important to note that the Python-based validator may lag behind the official JavaScript implementation available online. Additionally, the Python version only validates individual file paths - it doesn't support validation of an entire ```BIDS dataset```. For full dataset validation, it's recommended to use the online [BIDS Validator](https://bids-standard.github.io/bids-validator/).

In [20]:
from bids.layout import BIDSValidator

In [21]:
# When using the bids validator, the filepath MUST be relative to the top level bids directory
validator = BIDSValidator()
validator.is_bids('/sub-02/ses-retest/func/sub-02_ses-retest_task-covertverbgeneration_bold.nii.gz')

True

In [22]:
# Can decide if a filepath represents a file part of the specification
validator.is_file('/sub-02/ses-retest/func/sub-02_ses-retest_task-covertverbgeneration_bold.nii.gz')

True

In [23]:
# Can check if a file is at the top level of the dataset
validator.is_top_level('/dataset_description.json')

True

In [24]:
# or subject (or session) level
validator.is_subject_level('/dataset_description.json')

False

In [25]:
# Can decide if a filepath represents phenotypic data
validator.is_phenotypic('/sub-02/ses-test/anat/sub-02_ses-test_T1w.nii.gz')

False

#### Dependencies in Jupyter/Python
- Using the package [watermark](https://github.com/rasbt/watermark) to document system environment and software versions used in this notebook, alongside the Neurodesktop version extracted from the `JUPYTER_IMAGE` or `NEURODESKTOP_VERSION` environment variables.

In [26]:
import os

%load_ext watermark

%watermark
%watermark --iversions

neurodesktop_version = (
    os.environ.get('JUPYTER_IMAGE', '').split(':')[-1] or
    os.environ.get('NEURODESKTOP_VERSION', 'unknown')
)

print(f"Neurodesktop version: {neurodesktop_version}")

Last updated: 2026-04-09T04:09:44.540175+00:00

Python implementation: CPython
Python version       : 3.13.9
IPython version      : 9.7.0

Compiler    : GCC 14.3.0
OS          : Linux
Release     : 5.15.0-171-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 32
Architecture: 64bit

bids          : 0.21.0
bids_validator: 1.14.7.post0

Neurodesktop version: 2025-12-20